const medications = [
    { id: 114, en_name: "Hydrogen Peroxide", fa_name: "آب اکسیژنه", fa_desc: "شستشو و ضدعفونی کردن بریدگی‌ها و زخم‌های سطحی." },
    { id: 359, en_name: "Water for Injection", fa_name: "آب مقطر تزریقی", fa_desc: "برای حل کردن پودرهای دارویی و آمپول‌ها." },
    { id: 379, en_name: "Epinephrine (Pen)", fa_name: "اپی‌پن (EpiPen)", fa_desc: "قلم تزریق خودکار برای شوک آنافیلاکسی (حساسیت مرگبار)." },
    { id: 84, en_name: "Epinephrine", fa_name: "اپینفرین (آدرنالین)", fa_desc: "حیات‌بخش در شوک آنافیلاکسی (حساسیت شدید) و ایست قلبی." },
    { id: 89, en_name: "Ethambutol", fa_name: "اتامبوتول", fa_desc: "بخشی از رژیم درمانی بیماری سل." },
    { id: 363, en_name: "Atracurium", fa_name: "آتراکوریوم", fa_desc: "شل‌کننده عضلانی در بیهوشی و اتاق عمل." },
    { id: 307, en_name: "Atropine", fa_name: "آتروپین", fa_desc: "پادزهر اورژانسی برای مسمومیت با سموم کشاورزی (ارگانوفسفره) و افزایش ضربان قلب کند." },
    { id: 364, en_name: "Atropine", fa_name: "آتروپین", fa_desc: "داروی احیا قلبی در اورژانس و پادزهر مسمومیت با سموم کشاورزی." },
    { id: 19, en_name: "Atenolol", fa_name: "آتنولول", fa_desc: "کاهش فشار خون و ضربان قلب." },
    { id: 20, en_name: "Atorvastatin", fa_name: "آتورواستاتین", fa_desc: "کاهش کلسترول و چربی خون." },
    { id: 431, en_name: "Etomidate", fa_name: "اتومیدات", fa_desc: "داروی بیهوشی سریع برای لوله‌گذاری تنفسی مجروحانی که افت فشار خون دارند." },
    { id: 334, en_name: "Ethinylestradiol", fa_name: "اتینیل استرادیول", fa_desc: "جزء استروژنی در قرص‌های پیشگیری از بارداری." },
    { id: 302, en_name: "Adult Cold", fa_name: "آدالت کلد", fa_desc: "تسکین علائم سرماخوردگی، گرفتگی بینی و تب." },
    { id: 6, en_name: "Adalimumab", fa_name: "آدالیمومب", fa_desc: "درمان بیماری‌های خودایمنی مانند آرتریت روماتوئید و کرون." },
    { id: 472, en_name: "Edrophonium", fa_name: "ادروفونیوم", fa_desc: "تست تشخیصی اورژانسی برای بیماری میاستنی گراویس." },
    { id: 301, en_name: "Adenosine", fa_name: "آدنوزین", fa_desc: "تزریق اورژانسی برای تنظیم سریع ضربان قلب در آریتمی‌های فوق‌بطنی." },
    { id: 316, en_name: "Ergotamine C", fa_name: "ارگوتامین سی", fa_desc: "داروی اختصاصی برای قطع سریع حملات میگرن." },
    { id: 332, en_name: "Ergometrine", fa_name: "ارگومترین", fa_desc: "داروی اورژانسی برای کنترل خونریزی‌های شدید پس از زایمان یا سقط." },
    { id: 85, en_name: "Erythromycin", fa_name: "اریترومایسین", fa_desc: "درمان عفونت‌های چشمی و تنفسی." },
    { id: 333, en_name: "Erythromycin Topical", fa_name: "محلول اریترومایسین", fa_desc: "محلول موضعی برای درمان جوش و آکنه‌های عفونی." },
    { id: 21, en_name: "Azathioprine", fa_name: "آزاتیوپرین", fa_desc: "تضعیف سیستم ایمنی در بیماری‌های خودایمنی و پیوند اعضا." },
    { id: 365, en_name: "Azathioprine", fa_name: "آزاتیوپرین", fa_desc: "تضعیف سیستم ایمنی در پیوند اعضا." },
    { id: 90, en_name: "Ezetimibe", fa_name: "ازتمایب", fa_desc: "کاهش جذب کلسترول در روده برای کنترل چربی خون." },
    { id: 308, en_name: "Azelastine", fa_name: "آزلاستین", fa_desc: "اسپری بینی و قطره چشمی برای درمان سریع آلرژی‌های فصلی." },
    { id: 87, en_name: "Esomeprazole", fa_name: "ازومپرازول", fa_desc: "کاهش اسید معده، درمان رفلاکس و زخم گوارشی." },
    { id: 22, en_name: "Azithromycin", fa_name: "آزیترومایسین", fa_desc: "درمان عفونت‌های تنفسی، پوستی و عفونت‌های گوش." },
    { id: 387, en_name: "Spasmolytic", fa_name: "اسپاسمولیتیک", fa_desc: "گروه داروهای رفع‌کننده گرفتگی‌های روده‌ای و گوارشی." },
    { id: 18, en_name: "Aspirin", fa_name: "آسپرین", fa_desc: "رقیق‌کننده خون برای پیشگیری از سکته قلبی و مغزی." },
    { id: 384, en_name: "Salbutamol/Ipratropium", fa_name: "اسپری کامبی‌ونت", fa_desc: "ترکیب دو گشادکننده برونش برای حملات شدید آسم و انسداد ریه." },
    { id: 398, en_name: "Xylocaine", fa_name: "اسپری لیدوکائین (زیلوکائین)", fa_desc: "اسپری بی‌حس‌کننده برای دندان‌درد شدید یا بی‌حسی گلو." },
    { id: 249, en_name: "Spironolactone", fa_name: "اسپیرونولاکتون", fa_desc: "ادرارآور نگه‌دارنده پتاسیم، برای ورم و نارسایی قلبی." },
    { id: 3, en_name: "Acetazolamide", fa_name: "استازولامید", fa_desc: "درمان آب‌سیاه چشم (گلوکوم) و پیشگیری از ارتفاع‌زدگی." },
    { id: 2, en_name: "Acetaminophen", fa_name: "استامینوفن", fa_desc: "مسکن دردهای خفیف تا متوسط و پایین‌آورنده تب." },
    { id: 301, en_name: "Acetaminophen/Codeine", fa_name: "استامینوفن کدئین", fa_desc: "مسکن برای دردهای متوسط تا شدید و تب‌بر." },
    { id: 88, en_name: "Estradiol", fa_name: "استرادیول", fa_desc: "هورمون‌درمانی جایگزین در یائسگی و کمبود استروژن." },
    { id: 250, en_name: "Streptokinase", fa_name: "استرپتوکیناز", fa_desc: "داروی اورژانسی حل‌کننده لخته خون در سکته قلبی." },
    { id: 251, en_name: "Streptomycin", fa_name: "استرپتومایسین", fa_desc: "آنتی‌بیوتیک تزریقی قدیمی برای درمان سل و طاعون." },
    { id: 4, en_name: "Acetylcysteine", fa_name: "استیل سیستئین", fa_desc: "رقیق‌کننده خلط در بیماری‌های تنفسی و پادزهر مسمومیت با استامینوفن." },
    { id: 237, en_name: "Scopolamine", fa_name: "اسکوپولامین", fa_desc: "پیشگیری از حالت تهوع شدید و ماشین‌گرفتگی در سفر." },
    { id: 192, en_name: "Oseltamivir", fa_name: "اسلتامیویر (تامیفلو)", fa_desc: "داروی اختصاصی ضدویروس برای درمان و پیشگیری از آنفولانزا." },
    { id: 496, en_name: "Esmolol", fa_name: "اسمولول", fa_desc: "بتابلوکر وریدی با اثر بسیار کوتاه برای کنترل سریع تپش قلب وحشتناک در اورژانس." },
    { id: 86, en_name: "Escitalopram", fa_name: "اسیتالوپرام", fa_desc: "درمان افسردگی و اختلالات اضطرابی فراگیر." },
    { id: 457, en_name: "Acetic Acid Ear Drops", fa_name: "قطره اسید استیک", fa_desc: "درمان عفونت مجرای گوش ناشی از آب آلوده (گوش شناگر)." },
    { id: 440, en_name: "Alginic Acid", fa_name: "اسید آلژینیک (گاویسکون)", fa_desc: "شربت ایجادکننده سد فیزیکی روی اسید معده برای درمان فوری رفلاکس." },
    { id: 235, en_name: "Salicylic Acid", fa_name: "اسید سالیسیلیک", fa_desc: "محلول موضعی برای درمان زگیل، میخچه و لایه‌برداری." },
    { id: 340, en_name: "Fusidic Acid", fa_name: "اسید فوسیدیک", fa_desc: "پماد آنتی‌بیوتیک برای عفونت‌های پوستی موضعی و زردزخم." },
    { id: 99, en_name: "Folic Acid", fa_name: "اسید فولیک", fa_desc: "ویتامین B9، ضروری در دوران بارداری و کم‌خونی‌ها." },
    { id: 5, en_name: "Acyclovir", fa_name: "آسیکلوویر", fa_desc: "درمان عفونت‌های ویروسی مانند تبخال، زونا و آبله‌مرغان." },
    { id: 460, en_name: "Triamcinolone Paste", fa_name: "آفتین ژل / خمیر تریامسینولون", fa_desc: "مسکن و درمان‌کننده سریع آفت‌های دردناک دهانی." },
    { id: 378, en_name: "Ephedrine", fa_name: "افدرین", fa_desc: "درمان افت فشار خون در حین بیهوشی." },
    { id: 83, en_name: "Ephedrine", fa_name: "افدرین", fa_desc: "درمان افت فشار خون در حین بیهوشی." },
    { id: 187, en_name: "Ofloxacin", fa_name: "افلوکساسین", fa_desc: "آنتی‌بیوتیک قوی برای عفونت‌های چشم، گوش، ادراری و پروستات." },
    { id: 1, en_name: "Acarbose", fa_name: "آکاربوز", fa_desc: "کنترل قند خون در بیماران مبتلا به دیابت نوع ۲." },
    { id: 317, en_name: "Expectorant", fa_name: "اکسپکتورانت", fa_desc: "رقیق‌کننده خلط در سرفه‌های عفونی و سرماخوردگی." },
    { id: 318, en_name: "Expectorant Codeine", fa_name: "اکسپکتورانت کدئین", fa_desc: "درمان سرفه‌های شدید و خلط‌دار." },
    { id: 194, en_name: "Oxybutynin", fa_name: "اکسی‌بوتینین", fa_desc: "درمان تکرر ادرار، اسپاسم مثانه و بی‌اختیاری ادراری." },
    { id: 197, en_name: "Oxytocin", fa_name: "اکسی‌توسین", fa_desc: "هورمون اورژانسی برای القای زایمان و کنترل خونریزی‌های شدید پس از زایمان." },
    { id: 195, en_name: "Oxygen", fa_name: "اکسیژن (کپسول طبی)", fa_desc: "گاز حیاتی برای درمان افت اکسیژن خون (هیپوکسی) و اورژانس‌های تنفسی." },
    { id: 371, en_name: "Oxycodone", fa_name: "اکسی‌کدون", fa_desc: "مسکن مخدر بسیار قوی برای دردهای شدید سرطانی و پس از جراحی بزرگ." },
    { id: 196, en_name: "Oxymetazoline", fa_name: "اکسی‌متازولین", fa_desc: "قطره/اسپری بازکننده سریع گرفتگی بینی ناشی از سرماخوردگی." },
    { id: 331, en_name: "Econazole", fa_name: "اکونازول", fa_desc: "کرم ضد قارچ برای عفونت‌های پوستی لای انگشتان و کشاله ران." },
    { id: 193, en_name: "Oxazepam", fa_name: "اگزازپام", fa_desc: "آرام‌بخش کوتاه اثر، کنترل اضطراب و کاهش علائم ترک الکل." },
    { id: 302, en_name: "Albendazole", fa_name: "آلبندازول", fa_desc: "داروی ضد انگل وسیع‌الطیف برای درمان انواع کرم‌های روده‌ای و بافتی." },
    { id: 484, en_name: "Human Albumin", fa_name: "آلبومین انسانی", fa_desc: "سرم حیاتی برای نجات بیماران دچار سوختگی وسیع و نارسایی کبد." },
    { id: 10, en_name: "Alprazolam", fa_name: "آلپرازولام", fa_desc: "کاهش اضطراب شدید و درمان اختلالات پانیک." },
    { id: 420, en_name: "Alteplase (tPA)", fa_name: "آلتپلاز", fa_desc: "داروی حل‌کننده لخته خون در ساعات اولیه سکته مغزی یا قلبی." },
    { id: 303, en_name: "Alfacalcidol", fa_name: "آلفاکالسیدول", fa_desc: "فرم فعال ویتامین D برای بیمارانی که مشکلات کلیوی دارند." },
    { id: 464, en_name: "Isopropyl Alcohol 70%", fa_name: "الکل ایزوپروپیل ۷۰٪", fa_desc: "ضدعفونی‌کننده استاندارد پوست قبل از تزریق و پانسمان." },
    { id: 8, en_name: "Alendronate", fa_name: "آلندرونات", fa_desc: "پیشگیری و درمان پوکی استخوان." },
    { id: 9, en_name: "Allopurinol", fa_name: "آلوپورینول", fa_desc: "کاهش اسید اوریک خون و پیشگیری از حملات نقرس." },
    { id: 11, en_name: "Aluminum Hydroxide", fa_name: "آلومینیوم ام جی", fa_desc: "خنثی‌کننده اسید معده برای تسکین سوزش سر دل." },
    { id: 324, en_name: "Magnesium/Aluminum/Simethicone", fa_name: "آلومینیوم ام جی اس", fa_desc: "شربت آنتی‌اسید برای سوزش و نفخ معده." },
    { id: 303, en_name: "Aluminum MG S", fa_name: "آلومینیوم ام جی اس", fa_desc: "ضد اسید معده و برطرف‌کننده نفخ شدید." },
    { id: 12, en_name: "Amantadine", fa_name: "آمانتادین", fa_desc: "درمان بیماری پارکینسون و برخی عفونت‌های ویروسی." },
    { id: 189, en_name: "Omeprazole", fa_name: "امپرازول", fa_desc: "کاهش اسید معده، درمان قطعی زخم معده و رفلاکس شدید." },
    { id: 17, en_name: "Ampicillin", fa_name: "آمپی‌سیلین", fa_desc: "درمان عفونت‌های مجاری ادراری، تنفسی و گوارشی." },
    { id: 362, en_name: "Ampicillin/Sulbactam", fa_name: "آمپی‌سیلین سولباکتام", fa_desc: "آنتی‌بیوتیک وسیع‌الطیف برای عفونت‌های مقاوم." },
    { id: 306, en_name: "Amphotericin B", fa_name: "آمفوتریسین بی", fa_desc: "داروی ضد قارچ قوی تزریقی برای عفونت‌های قارچی سیستمیک و کشنده." },
    { id: 494, en_name: "Amphotericin B", fa_name: "آمفوتریسین بی", fa_desc: "تزریق حیاتی برای درمان عفونت‌های قارچی بسیار شدید (مثل موکورمایکوزیس/قارچ سیاه)." },
    { id: 333, en_name: "Omega 3", fa_name: "امگا ۳", fa_desc: "مکمل اسیدهای چرب برای سلامت قلب و کاهش التهاب." },
    { id: 15, en_name: "Amlodipine", fa_name: "آملودیپین", fa_desc: "کاهش فشار خون بالا و درمان دردهای قفسه سینه." },
    { id: 16, en_name: "Amoxicillin", fa_name: "آموکسی سیلین", fa_desc: "آنتی‌بیوتیک برای درمان عفونت‌های باکتریایی شایع." },
    { id: 14, en_name: "Amitriptyline", fa_name: "آمی‌تریپتیلین", fa_desc: "درمان افسردگی، دردهای عصبی و پیشگیری از میگرن." },
    { id: 304, en_name: "Amikacin", fa_name: "آمیکاسین", fa_desc: "آنتی‌بیوتیک تزریقی قوی برای عفونت‌های مقاوم بیمارستانی." },
    { id: 411, en_name: "Amyl Nitrite", fa_name: "آمیل نیتریت (آمپول استنشاقی)", fa_desc: "پادزهر فوری استنشاقی برای مسمومیت با گاز سیانور." },
    { id: 488, en_name: "Aminocaproic Acid", fa_name: "آمینرکاپروئیک اسید", fa_desc: "داروی منعقدکننده خون برای توقف خونریزی‌های مهارنشدنی جراحی." },
    { id: 305, en_name: "Aminophylline", fa_name: "آمینوفیلین", fa_desc: "گشادکننده برونش برای درمان اورژانسی حملات شدید آسم." },
    { id: 13, en_name: "Amiodarone", fa_name: "آمیودارون", fa_desc: "تنظیم‌کننده ضربان قلب در آریتمی‌های خطرناک." },
    { id: 361, en_name: "Amiodarone (Injection)", fa_name: "آمیودارون (آمپول)", fa_desc: "داروی اورژانسی برای تنظیم ریتم‌های خطرناک قلب." },
    { id: 81, en_name: "Enalapril", fa_name: "انالاپریل", fa_desc: "کاهش فشار خون بالا و نارسایی قلبی." },
    { id: 266, en_name: "Tetanus Antitoxin", fa_name: "آنتی‌توکسین کزاز", fa_desc: "سرم اورژانسی ضد کزاز برای خنثی کردن سم در زخم‌های آلوده." },
    { id: 190, en_name: "Ondansetron", fa_name: "اندانسترون", fa_desc: "ضد تهوع و استفراغ بسیار قوی (مخصوصاً پس از جراحی یا شیمی‌درمانی)." },
    { id: 120, en_name: "Insulin (Regular/NPH)", fa_name: "انسولین", fa_desc: "هورمون تنظیم‌کننده قند خون در دیابت نوع ۱ و دیابت‌های وابسته." },
    { id: 82, en_name: "Enoxaparin", fa_name: "انوکساپارین", fa_desc: "رقیق‌کننده خون تزریقی برای جلوگیری از لخته شدن." },
    { id: 368, en_name: "Nystatin/Triamcinolone", fa_name: "پماد ان ان (NN)", fa_desc: "پماد ترکیبی برای سوختگی‌های قارچی شدید پای نوزاد و نواحی مرطوب پوست." },
    { id: 287, en_name: "Ursodeoxycholic Acid", fa_name: "اورسودوکسی‌کولیک اسید", fa_desc: "حل‌کننده سنگ‌های صفرای کوچک و درمان مشکلات کبدی." },
    { id: 370, en_name: "Orphenadrine", fa_name: "اورفنادرین", fa_desc: "شل‌کننده عضلانی برای دردهای اسکلتی و اسپاسم‌های ناشی از ضربه." },
    { id: 186, en_name: "Octreotide", fa_name: "اوکترئوتاید", fa_desc: "کنترل خونریزی‌های شدید گوارشی (واریس مری) و برخی تومورها." },
    { id: 188, en_name: "Olanzapine", fa_name: "اولانزاپین", fa_desc: "کنترل علائم اسکیزوفرنی، توهم و اختلال دوقطبی." },
    { id: 369, en_name: "Olopatadine", fa_name: "اولوپاتادین", fa_desc: "قطره چشمی ضدحساسیت قوی برای آلرژی‌های مزمن چشمی." },
    { id: 334, en_name: "Oral Rehydration Salts (ORS)", fa_name: "او آر اس (ORS)", fa_desc: "پودر جبران آب و الکترولیت بدن در زمان اسهال شدید." },
    { id: 347, en_name: "Iron Dextran", fa_name: "آهن دکستران", fa_desc: "آمپول آهن تزریقی برای کم‌خونی‌های شدید که به قرص جواب نمی‌دهند." },
    { id: 321, en_name: "Iron+Folic Acid", fa_name: "آهن و اسید فولیک", fa_desc: "مکمل ترکیبی برای کم‌خونی‌های شدید و دوران بارداری." },
    { id: 122, en_name: "Iron (Ferrous)", fa_name: "آهن (قرص/شربت)", fa_desc: "تامین آهن بدن و درمان کم‌خونی ناشی از فقر آهن." },
    { id: 117, en_name: "Ibuprofen", fa_name: "ایبوپروفن", fa_desc: "مسکن، پایین‌آورنده تب و ضدالتهاب مفاصل." },
    { id: 121, en_name: "Ipratropium", fa_name: "ایپراتروپیوم", fa_desc: "اسپری گشادکننده برونش برای بیماران آسمی و برونشیت." },
    { id: 497, en_name: "Isoprenaline", fa_name: "ایزوپرنالین", fa_desc: "داروی اورژانسی برای افزایش ضربان قلبی که به شدت کند شده است." },
    { id: 124, en_name: "Isotretinoin", fa_name: "ایزوترتینوئین (راکوتان)", fa_desc: "درمان آکنه‌های شدید، کیستیک و مقاوم به درمان." },
    { id: 388, en_name: "Isosorbide Dinitrate", fa_name: "ایزوسورباید", fa_desc: "گشادکننده عروق برای پیشگیری و درمان دردهای قلبی." },
    { id: 123, en_name: "Isosorbide Dinitrate", fa_name: "ایزوسورباید", fa_desc: "گشادکننده عروق برای پیشگیری و درمان دردهای قلبی (آنژین)." },
    { id: 348, en_name: "Isosorbide Mononitrate", fa_name: "ایزوسورباید مونو نیترات", fa_desc: "پیشگیری طولانی‌مدت از حملات درد قفسه سینه در بیماران قلبی." },
    { id: 468, en_name: "Isoflurane", fa_name: "ایزوفلوران", fa_desc: "گاز بیهوشی استنشاقی (جایگزین ارزان‌تر برای شرایط بحرانی)." },
    { id: 118, en_name: "Imipramine", fa_name: "ایمی‌پرامین", fa_desc: "درمان افسردگی و کنترل شب‌ادراری در کودکان." },
    { id: 346, en_name: "Imipenem", fa_name: "ایمی‌پنم", fa_desc: "آنتی‌بیوتیک تزریقی فوق‌العاده قوی برای عفونت‌های مرگبار بیمارستانی." },
    { id: 119, en_name: "Indomethacin", fa_name: "ایندومتاسین", fa_desc: "مسکن و ضدالتهاب بسیار قوی برای حملات نقرس و آرتریت." },
    { id: 320, en_name: "Indomethacin (Suppository)", fa_name: "ایندومتاسین (شیاف)", fa_desc: "کاهش سریع دردهای مفصلی و تب‌های مقاوم." },
    { id: 349, en_name: "Ivermectin", fa_name: "ایورمکتین", fa_desc: "داروی ضد انگل برای درمان گال مقاوم و عفونت‌های انگلی خاص." },
    { id: 447, en_name: "Bacitracin", fa_name: "باسیتراسین", fa_desc: "پماد آنتی‌بیوتیک ساده برای بریدگی‌ها و خراش‌های سطحی." },
    { id: 23, en_name: "Baclofen", fa_name: "باکلوفن", fa_desc: "شل‌کننده عضلانی برای رفع اسپاسم و گرفتگی‌های شدید." },
    { id: 453, en_name: "Betaxolol", fa_name: "بتاکسولول", fa_desc: "قطره چشمی برای کنترل بیماری آب‌سیاه (گلوکوم)." },
    { id: 25, en_name: "Betamethasone", fa_name: "بتامتازون", fa_desc: "کاهش التهابات شدید پوستی و آلرژی‌ها." },
    { id: 28, en_name: "Bromhexine", fa_name: "برم هگزین", fa_desc: "خلط‌آور و رقیق‌کننده ترشحات تنفسی." },
    { id: 454, en_name: "Brimonidine", fa_name: "بریمونیدین", fa_desc: "قطره چشمی برای کاهش فشار چشم و بند آوردن خونریزی‌های ریز چشمی." },
    { id: 24, en_name: "Beclomethasone", fa_name: "بکلومتازون", fa_desc: "کنترل طولانی‌مدت آسم و رینیت آلرژیک." },
    { id: 490, en_name: "Balsam Peru / Castor Oil", fa_name: "پماد بلسان پرو / روغن کرچک", fa_desc: "پماد ترمیم‌کننده عالی برای زخم‌های بستر و زخم‌های پوستی کند‌درمان." },
    { id: 463, en_name: "Benzalkonium Chloride", fa_name: "بنزالکونیوم کلراید", fa_desc: "ضدعفونی‌کننده زخم‌ها و شستشوی محل گازگرفتگی حیوانات." },
    { id: 30, en_name: "Buprenorphine", fa_name: "بوپرنورفین", fa_desc: "تسکین دردهای شدید و کمک به ترک اعتیاد." },
    { id: 31, en_name: "Bupropion", fa_name: "بوپروپیون", fa_desc: "درمان افسردگی و کمک به ترک سیگار." },
    { id: 311, en_name: "Bupivacaine", fa_name: "بوپیواکائین", fa_desc: "بی‌حس‌کننده موضعی و نخاعی طولانی‌اثر برای اعمال جراحی و زایمان بدون درد." },
    { id: 469, en_name: "Bupivacaine Heavy", fa_name: "بوپیواکائین هوی (نخاعی)", fa_desc: "آمپول بی‌حسی نخاعی (اسپاینال) برای جراحی‌های پایین‌تنه بدون نیاز به بیهوشی عمومی." },
    { id: 29, en_name: "Budesonide", fa_name: "بودزوناید", fa_desc: "کاهش التهاب در آسم و بیماری‌های التهابی روده." },
    { id: 366, en_name: "Budesonide (Inhaler)", fa_name: "بودزوناید (اسپری)", fa_desc: "کاهش التهاب راه‌های هوایی در آسم." },
    { id: 26, en_name: "Bisacodyl", fa_name: "بیزاکودیل", fa_desc: "ملین برای درمان یبوست حاد و تخلیه روده." },
    { id: 27, en_name: "Bisoprolol", fa_name: "بیزوپرولول", fa_desc: "کنترل فشار خون و نارسایی قلبی." },
    { id: 436, en_name: "Bismuth Subsalicylate", fa_name: "بیسموت ساب‌سالیسیلات", fa_desc: "درمان اسهال مسافرتی، تهوع و محافظت از دیواره معده." },
    { id: 310, en_name: "Bismuth Subcitrate", fa_name: "بیسموت ساب‌سیترات", fa_desc: "پوشش‌دهنده معده برای درمان زخم معده و ریشه‌کنی میکروب هلیکوباکتر." },
    { id: 305, en_name: "Bismuth Subcitrate", fa_name: "بیسموت ساب‌سیترات", fa_desc: "درمان زخم معده و ریشه‌کنی میکروب هلیکوباکتر." },
    { id: 346, en_name: "Sodium Chloride (Nasal)", fa_name: "قطره بینی سدیم کلراید", fa_desc: "شستشو و مرطوب کردن مجاری تنفسی نوزادان و بزرگسالان." },
    { id: 309, en_name: "B Complex", fa_name: "ب کمپلکس", fa_desc: "آمپول/قرص ویتامین‌های گروه B برای تقویت اعصاب و رفع خستگی شدید." },
    { id: 304, en_name: "B-Complex", fa_name: "ب کمپلکس", fa_desc: "تقویت سیستم عصبی و جبران کمبود ویتامین‌های گروه ب." },
    { id: 487, en_name: "Botulism Antitoxin", fa_name: "پادزهر بوتولیسم", fa_desc: "پادزهر مسمومیت غذایی کشنده (ناشی از کنسروهای فاسد) یا حملات بیولوژیک." },
    { id: 486, en_name: "Diphtheria Antitoxin", fa_name: "پادزهر دیفتری", fa_desc: "سرم خنثی‌کننده سم در بیماری خفه‌کننده دیفتری." },
    { id: 405, en_name: "Scorpion Antivenom", fa_name: "پادزهر عقرب‌گزیدگی", fa_desc: "سرم نجات‌بخش برای نیش عقرب‌های خطرناک." },
    { id: 404, en_name: "Snake Antivenom", fa_name: "پادزهر مارگزیدگی", fa_desc: "خنثی‌کننده زهر مارهای سمی در مناطق بیابانی و کوهستانی." },
    { id: 199, en_name: "Paracetamol", fa_name: "پاراستامول (استامینوفن)", fa_desc: "ایمن‌ترین مسکن و تب‌بر عمومی برای تمام سنین." },
    { id: 198, en_name: "Pantoprazole", fa_name: "پانتوپرازول", fa_desc: "مهارکننده قوی اسید معده، درمان زخم‌ها و پیشگیری از خونریزی گوارشی." },
    { id: 372, en_name: "Pancreatin", fa_name: "پانکراتین", fa_desc: "آنزیم‌های گوارشی برای کمک به هضم غذا در نارسایی لوزالمعده." },
    { id: 378, en_name: "Potassium Chloride", fa_name: "پتاسیم کلراید", fa_desc: "جبران افت شدید پتاسیم خون (تزریق آن باید بسیار با احتیاط و رقیق شده باشد)." },
    { id: 208, en_name: "Prazosin", fa_name: "پرازوسین", fa_desc: "کاهش فشار خون و درمان بزرگی خوش‌خیم پروستات." },
    { id: 491, en_name: "Prasugrel", fa_name: "پراسوگرل", fa_desc: "ضد پلاکت سریع‌الاثر برای بیمارانی که دچار سکته قلبی شده و نیازمند استنت هستند." },
    { id: 379, en_name: "Pralidoxime", fa_name: "پرالیدوکسیم", fa_desc: "پادزهر تخصصی در کنار آتروپین برای مسمومیت با سموم حشره‌کش و گازهای جنگی." },
    { id: 207, en_name: "Pramipexole", fa_name: "پرامی‌پکسول", fa_desc: "درمان بیماری پارکینسون و سندرم پای بی‌قرار." },
    { id: 209, en_name: "Prednisolone", fa_name: "پردنیزولون", fa_desc: "کورتون خوراکی برای کاهش سریع التهابات شدید و آلرژی‌ها." },
    { id: 201, en_name: "Permethrin", fa_name: "پرمترین", fa_desc: "لوسیون/شامپو برای درمان قطعی گال (جرب) و شپش." },
    { id: 429, en_name: "Potassium Permanganate", fa_name: "پرمنگنات پتاسیم", fa_desc: "پودر ضدعفونی‌کننده قوی برای شستشوی زخم‌های عفونی و قارچی خیس." },
    { id: 449, en_name: "Proparacaine", fa_name: "پروپاراکائین", fa_desc: "قطره بی‌حس‌کننده فوری چشم برای شستشو یا خارج کردن جسم خارجی." },
    { id: 213, en_name: "Propranolol", fa_name: "پروپرانولول", fa_desc: "کاهش تپش قلب ناشی از اضطراب، کنترل فشار خون و پیشگیری از میگرن." },
    { id: 343, en_name: "Propanolol", fa_name: "پروپرانولول", fa_desc: "کنترل تپش قلب، لرزش دست و پیشگیری از میگرن." },
    { id: 212, en_name: "Propofol", fa_name: "پروپوفول", fa_desc: "داروی بیهوشی سریع در اورژانس و اتاق عمل." },
    { id: 214, en_name: "Propylthiouracil", fa_name: "پروپیل تیواوراسیل", fa_desc: "درمان پرکاری تیروئید." },
    { id: 342, en_name: "Proctoseryl", fa_name: "پروکتوسریل (پماد)", fa_desc: "درمان درد، خارش و التهاب هموروئید (بواسیر)." },
    { id: 380, en_name: "Prochlorperazine", fa_name: "پروکلرپرازین", fa_desc: "درمان حالت تهوع و استفراغ شدید، به ویژه در میگرن." },
    { id: 211, en_name: "Promethazine", fa_name: "پرومتازین", fa_desc: "ضدحساسیت، ضد تهوع قوی و آرام‌بخش." },
    { id: 381, en_name: "Promethazine/Dextromethorphan", fa_name: "شربت پرومتازین دکسترومتورفان", fa_desc: "درمان سرفه‌های خشک و شدید در سرماخوردگی‌ها." },
    { id: 210, en_name: "Pregabalin", fa_name: "پره‌گابالین", fa_desc: "درمان دردهای مزمن عصبی (نوروپاتی) و کمک به کنترل تشنج." },
    { id: 377, en_name: "Polymyxin B/Hydrocortisone", fa_name: "پلی‌میکسین اچ", fa_desc: "قطره گوش برای عفونت‌ها و التهاب‌های مجرای خارجی گوش." },
    { id: 340, en_name: "Polymyxin/Bacitracin", fa_name: "پلی‌میکسین/باسیتراسین", fa_desc: "پماد آنتی‌بیوتیک ترکیبی برای زخم‌های پوستی." },
    { id: 374, en_name: "Pentoxifylline", fa_name: "پنتوکسی‌فیلین", fa_desc: "بهبود جریان خون در اندام‌ها و کاهش درد پا هنگام راه رفتن (لنگیدن متناوب)." },
    { id: 200, en_name: "Penicillin G/V", fa_name: "پنی‌سیلین (تزریقی/خوراکی)", fa_desc: "آنتی‌بیوتیک کلاسیک برای عفونت‌های شدید استرپتوکوکی (گلو درد چرکی) و سیفلیس." },
    { id: 336, en_name: "Penicillin 3.3.6", fa_name: "پنی‌سیلین ۳.۳.۶", fa_desc: "آنتی‌بیوتیک تزریقی ترکیبی برای عفونت‌های باکتریایی." },
    { id: 337, en_name: "Penicillin 6.3.3", fa_name: "پنی‌سیلین ۶.۳.۳", fa_desc: "نسخه قوی‌تر پنی‌سیلین ترکیبی." },
    { id: 373, en_name: "Penicillin 800,000", fa_name: "پنی‌سیلین ۸۰۰,۰۰۰", fa_desc: "آنتی‌بیوتیک تزریقی طولانی‌اثر برای درمان گلودرد چرکی و عفونت‌های استرپتوکوکی." },
    { id: 191, en_name: "ORS (Oral Rehydration)", fa_name: "پودر او آر اس", fa_desc: "حیاتی‌ترین محلول برای جبران آب و املاح از دست رفته در اسهال و استفراغ." },
    { id: 206, en_name: "Povidone-Iodine", fa_name: "پوویدون آیوداین (بتادین)", fa_desc: "محلول ضدعفونی‌کننده قوی برای شستشوی زخم‌ها و بریدگی‌ها." },
    { id: 217, en_name: "Pyrazinamide", fa_name: "پیرازینامید", fa_desc: "آنتی‌بیوتیک تخصصی برای درمان بیماری سل." },
    { id: 216, en_name: "Pyrantel", fa_name: "پیرانتل", fa_desc: "داروی ضد انگل ایمن برای درمان کرمک." },
    { id: 205, en_name: "Piroxicam", fa_name: "پیروکسیکام", fa_desc: "مسکن و ضدالتهاب طولانی‌اثر برای مفاصل و استخوان." },
    { id: 339, en_name: "Piroxicam (Gel)", fa_name: "پیروکسیکام (ژل)", fa_desc: "کاهش موضعی دردهای عضلانی و آرتروز." },
    { id: 382, en_name: "Pyridostigmine", fa_name: "پیریدوستیگمین", fa_desc: "داروی اصلی برای کنترل ضعف عضلانی در بیماری میاستنی گراویس." },
    { id: 498, en_name: "Pyridostigmine", fa_name: "پیریدوستیگمین (قرص پیش‌گیری)", fa_desc: "استفاده در ارتش‌ها به عنوان قرص پیشگیری قبل از حمله با گاز اعصاب (سومان)." },
    { id: 218, en_name: "Pyridoxine", fa_name: "پیریدوکسین (ویتامین B6)", fa_desc: "کاهش تهوع بارداری و پیشگیری از آسیب‌های عصبی ناشی از داروها." },
    { id: 204, en_name: "Pilocarpine", fa_name: "پیلوکارپین", fa_desc: "قطره چشمی برای کاهش اورژانسی فشار داخل چشم (آب‌سیاه)." },
    { id: 257, en_name: "Tadalafil", fa_name: "تادالافیل", fa_desc: "درمان اختلال نعوظ و بزرگی پروستات." },
    { id: 256, en_name: "Tacrolimus", fa_name: "تاکرولیموس", fa_desc: "جلوگیری از رد پیوند اعضا و پماد برای اگزماهای شدید." },
    { id: 259, en_name: "Tamsulosin", fa_name: "تامسولوسین", fa_desc: "شل‌کننده عضلات پروستات برای تسهیل دفع ادرار و دفع سنگ." },
    { id: 258, en_name: "Tamoxifen", fa_name: "تاموکسیفن", fa_desc: "پیشگیری و درمان سرطان پستان." },
    { id: 268, en_name: "Tetracycline", fa_name: "تتراسایکلین", fa_desc: "آنتی‌بیوتیک برای درمان آکنه، وبا و عفونت‌های تنفسی." },
    { id: 352, en_name: "Tetracycline (Eye Ointment)", fa_name: "تتراسایکلین (پماد چشمی)", fa_desc: "درمان عفونت‌های باکتریایی چشم مانند گل‌مژه." },
    { id: 391, en_name: "Tetracaine", fa_name: "تتراکائین", fa_desc: "قطره بی‌حس‌کننده موضعی چشم برای معاینه و درآوردن جسم خارجی." },
    { id: 267, en_name: "Tetracaine", fa_name: "تتراکائین", fa_desc: "قطره بی‌حس‌کننده چشم برای معاینه و خروج جسم خارجی." },
    { id: 351, en_name: "Tetracaine (Eye Drop)", fa_name: "تتراکائین (قطره)", fa_desc: "بی‌حس‌کننده موضعی چشم برای معاینات و خروج جسم خارجی." },
    { id: 455, en_name: "Tetrahydrozoline", fa_name: "تتراهیدروزولین (نفازولین)", fa_desc: "برطرف‌کننده فوری قرمزی چشم خسته." },
    { id: 280, en_name: "Trazodone", fa_name: "ترازودون", fa_desc: "ضد افسردگی و داروی کمک‌کننده به خواب." },
    { id: 262, en_name: "Terazosin", fa_name: "ترازوسین", fa_desc: "درمان فشار خون و بزرگی خوش‌خیم پروستات." },
    { id: 278, en_name: "Tramadol", fa_name: "ترامادول", fa_desc: "مسکن قوی برای دردهای متوسط تا شدید (با خطر تشنج در دوز بالا)." },
    { id: 393, en_name: "Tranexamic Acid", fa_name: "کپسول ترانسید", fa_desc: "کنترل خونریزی‌های قاعدگی بسیار شدید در زنان." },
    { id: 279, en_name: "Tranexamic Acid", fa_name: "ترانگزامیک اسید", fa_desc: "داروی اورژانسی برای بند آوردن خونریزی‌های شدید داخلی و خارجی." },
    { id: 264, en_name: "Terbutaline", fa_name: "تربوتالین", fa_desc: "گشادکننده راه‌های هوایی و جلوگیری از زایمان زودرس." },
    { id: 263, en_name: "Terbinafine", fa_name: "تربینافین", fa_desc: "داروی ضدقارچ قوی برای عفونت‌های ناخن و پوست." },
    { id: 394, en_name: "Tretinoin", fa_name: "ترتینوئین", fa_desc: "کرم موضعی برای درمان آکنه و لایه‌برداری پوست." },
    { id: 477, en_name: "Terlipressin", fa_name: "ترلی‌پرسین", fa_desc: "داروی کلیدی برای متوقف کردن خونریزی واریس مری." },
    { id: 286, en_name: "Tropicamide", fa_name: "تروپیکامید", fa_desc: "قطره گشادکننده مردمک چشم برای معاینات پزشکی." },
    { id: 282, en_name: "Triamterene", fa_name: "تریامترن", fa_desc: "ادرارآور ضعیف که پتاسیم بدن را حفظ می‌کند." },
    { id: 353, en_name: "Triamterene-H", fa_name: "تریامترن اچ", fa_desc: "داروی ادرارآور پرکاربرد برای تنظیم فشار خون." },
    { id: 281, en_name: "Triamcinolone", fa_name: "تریامسینولون", fa_desc: "کورتون قوی (پماد/آمپول) برای حساسیت‌های شدید و التهاب مفصل." },
    { id: 365, en_name: "Neomycin/Polymyxin/Bacitracin", fa_name: "پماد تریپل کراون (تریپامایسین)", fa_desc: "پماد آنتی‌بیوتیک سه‌گانه برای جلوگیری از عفونت بریدگی‌ها و سوختگی‌های سطحی." },
    { id: 283, en_name: "Trifluoperazine", fa_name: "تری‌فلوپرازین", fa_desc: "کنترل اسکیزوفرنی و توقف تهوع‌های بسیار شدید." },
    { id: 395, en_name: "Trihexyphenidyl", fa_name: "تری‌هگزی‌فنیدیل", fa_desc: "درمان پارکینسون و رفع خشکی عضلات ناشی از داروهای اعصاب." },
    { id: 284, en_name: "Trihexyphenidyl", fa_name: "تری‌هگزی‌فنیدیل", fa_desc: "درمان پارکینسون و کاهش عوارض خشکی عضلات داروهای اعصاب." },
    { id: 265, en_name: "Testosterone", fa_name: "تستوسترون", fa_desc: "هورمون‌درمانی در مردان." },
    { id: 403, en_name: "Water Purification Tablets", fa_name: "قرص تصفیه آب (هالازون/کلرامین)", fa_desc: "ضدعفونی‌کننده آب‌های مشکوک برای جلوگیری از وبا و اسهال خونی در شرایط جنگی." },
    { id: 260, en_name: "Telmisartan", fa_name: "تلمیسارتان", fa_desc: "کاهنده فشار خون بالا و محافظ کلیه." },
    { id: 261, en_name: "Tenoxicam", fa_name: "تنوکسیکام", fa_desc: "مسکن و ضدالتهاب طولانی‌اثر برای دردهای مفصلی." },
    { id: 274, en_name: "Tobramycin", fa_name: "توبرامایسین", fa_desc: "آنتی‌بیوتیک قوی (قطره/آمپول) برای عفونت‌های مقاوم." },
    { id: 276, en_name: "Topiramate", fa_name: "توپیرامات", fa_desc: "ضد تشنج و داروی بسیار موثر برای پیشگیری از میگرن." },
    { id: 277, en_name: "Torsemide", fa_name: "تورسماید", fa_desc: "ادرارآور قوی برای کاهش ورم در نارسایی قلبی." },
    { id: 446, en_name: "Tolperisone", fa_name: "تولپریسون", fa_desc: "شل‌کننده عضلانی مرکزی برای گرفتگی‌های دردناک ستون فقرات." },
    { id: 275, en_name: "Tolterodine", fa_name: "تولترودین", fa_desc: "درمان تکرر ادرار و مثانه بیش‌فعال." },
    { id: 348, en_name: "Spironolactone/Hydrochlorothiazide", fa_name: "تیازید/اسپیرونولاکتون", fa_desc: "ادرارآور ترکیبی برای کاهش ورم و فشار خون." },
    { id: 270, en_name: "Thiamine", fa_name: "تیامین (ویتامین B1)", fa_desc: "حیاتی برای پیشگیری از آسیب مغزی در سوءتغذیه." },
    { id: 492, en_name: "Tirofiban", fa_name: "تیروفیبان", fa_desc: "داروی ضد پلاکت وریدی برای شرایط فوق‌حاد کرونری (بستری)." },
    { id: 273, en_name: "Tizanidine", fa_name: "تیزانیدین", fa_desc: "شل‌کننده عضلانی قوی برای اسپاسم‌های نخاعی و ام‌اس." },
    { id: 421, en_name: "Ticagrelor", fa_name: "تیکاگرلور", fa_desc: "داروی ضد پلاکت قوی برای جلوگیری از لخته پس از سکته حاد قلبی." },
    { id: 424, en_name: "Teicoplanin", fa_name: "تیکوپلانین", fa_desc: "درمان عفونت‌های استخوانی و خونی شدید ناشی از باکتری‌های مقاوم (MRSA)." },
    { id: 272, en_name: "Timolol", fa_name: "تیمولول", fa_desc: "قطره چشمی برای کاهش فشار چشم در بیماری آب سیاه." },
    { id: 392, en_name: "Tinidazole", fa_name: "تینیدازول", fa_desc: "آنتی‌بیوتیک مشابه مترونیدازول برای عفونت‌های انگلی و آمیبی." },
    { id: 271, en_name: "Thiopental", fa_name: "تیوپنتال", fa_desc: "داروی بیهوشی بسیار سریع." },
    { id: 439, en_name: "Tiotropium", fa_name: "تیوتروپیوم", fa_desc: "اسپری استنشاقی برای کنترل تنگی نفس در جانبازان شیمیایی و بیماران ریوی." },
    { id: 269, en_name: "Theophylline", fa_name: "تئوفیلین", fa_desc: "گشادکننده برونش برای آسم و بیماری‌های مزمن ریوی." },
    { id: 422, en_name: "Piperacillin/Tazobactam", fa_name: "تَزوسین", fa_desc: "آنتی‌بیوتیک تزریقی وسیع‌الطیف برای عفونت‌های شدید خون (سپسیس) در مجروحان جنگی." },
    { id: 102, en_name: "Gemfibrozil", fa_name: "جم فیبروزیل", fa_desc: "کاهش تری‌گلیسیرید و کلسترول خون." },
    { id: 103, en_name: "Gentamicin", fa_name: "جنتامایسین", fa_desc: "آنتی‌بیوتیک برای عفونت‌های شدید باکتریایی (قطره چشم/گوش یا آمپول)." },
    { id: 489, en_name: "Fibrin Sealant", fa_name: "چسب فیبرین", fa_desc: "چسب بافتی جراحی برای متوقف کردن خونریزی اندام‌های داخلی پاره شده." },
    { id: 450, en_name: "Ketotifen Eye Drops", fa_name: "قطره چشمی کتوتیفن", fa_desc: "درمان خارش شدید و قرمزی چشم در آلرژی‌ها و تماس با گرد و غبار." },
    { id: 79, en_name: "Doxycycline", fa_name: "داکسی سایکلین", fa_desc: "درمان عفونت‌های پوستی (آکنه)، تنفسی و بیماری لایم." },
    { id: 325, en_name: "Dantrolene", fa_name: "دانترولن", fa_desc: "شل‌کننده عضلانی خاص برای درمان اورژانسی هایپرترمی بدخیم در اتاق عمل." },
    { id: 372, en_name: "Dantrolene", fa_name: "دانترولن", fa_desc: "درمان اورژانسی تب بدخیم و اسپاسم‌های شدید." },
    { id: 329, en_name: "Dimethicone", fa_name: "دایمتیکون", fa_desc: "کرم محافظ پوست برای جلوگیری از ادرار سوختگی و زخم بستر." },
    { id: 434, en_name: "Droperidol", fa_name: "دروپریدول", fa_desc: "کنترل سریع پرخاشگری شدید، جنون حاد و تهوع مقاوم در اورژانس." },
    { id: 326, en_name: "Desmopressin", fa_name: "دزموپرسین", fa_desc: "اسپری بینی برای درمان شب‌ادراری و دیابت بی‌مزه." },
    { id: 373, en_name: "Deferoxamine", fa_name: "دسفرال (دفرواکسامین)", fa_desc: "پادزهر مسمومیت با آهن و دفع آهن اضافی در تالاسمی." },
    { id: 415, en_name: "Deferoxamine", fa_name: "دفرروکس‌آمین", fa_desc: "پادزهر مسمومیت کشنده با قرص آهن در کودکان." },
    { id: 313, en_name: "Dexpanthenol", fa_name: "دکسپانتنول", fa_desc: "پماد برای ترمیم زخم‌های سطحی، سوختگی و خشکی شدید پوست." },
    { id: 64, en_name: "Dextromethorphan", fa_name: "دکسترومتورفان", fa_desc: "سرکوب سرفه‌های خشک و بدون خلط." },
    { id: 442, en_name: "Dexketoprofen", fa_name: "دکس‌کتوپروفن", fa_desc: "تسکین سریع دردهای اسکلتی عضلانی و دردهای دندانی." },
    { id: 433, en_name: "Dexmedetomidine", fa_name: "دکسمدتومیدین", fa_desc: "آرام‌بخش بیماران بستری در بخش مراقبت‌های ویژه (ICU) بدون قطع تنفس." },
    { id: 63, en_name: "Dexamethasone", fa_name: "دگزامتازون", fa_desc: "کاهش التهابات شدید، آلرژی‌ها و تورم راه‌های هوایی." },
    { id: 376, en_name: "Dobutamine", fa_name: "دوبوتامین", fa_desc: "تحریک قلب در شوک‌های خطرناک." },
    { id: 73, en_name: "Dobutamine", fa_name: "دوبوتامین", fa_desc: "تحریک قلب در شوک و نارسایی حاد قلبی (بیمارستانی)." },
    { id: 377, en_name: "Dopamine", fa_name: "دوپامین", fa_desc: "افزایش فشار خون در وضعیت‌های شوک و اورژانس." },
    { id: 76, en_name: "Dopamine", fa_name: "دوپامین", fa_desc: "افزایش فشار خون در وضعیت‌های شوک و اورژانس." },
    { id: 77, en_name: "Doxazosin", fa_name: "دوکسازوسین", fa_desc: "درمان بزرگی خوش‌خیم پروستات و فشار خون بالا." },
    { id: 78, en_name: "Doxepin", fa_name: "دوکسپین", fa_desc: "درمان افسردگی، اضطراب و اختلالات خواب." },
    { id: 80, en_name: "Duloxetine", fa_name: "دولوکستین", fa_desc: "درمان افسردگی، اضطراب و دردهای عصبی مزمن." },
    { id: 74, en_name: "Domperidone", fa_name: "دومپریدون", fa_desc: "درمان تهوع، استفراغ و احساس پری معده." },
    { id: 75, en_name: "Donepezil", fa_name: "دونپزیل", fa_desc: "بهبود علائم زوال عقل در آلزایمر." },
    { id: 65, en_name: "Diazepam", fa_name: "دیازپام", fa_desc: "آرام‌بخش، کنترل تشنج و کاهش اسپاسم عضلانی." },
    { id: 67, en_name: "Dicyclomine", fa_name: "دیسیکلومین", fa_desc: "رفع دل‌پیچه، دردهای شکمی و سندرم روده تحریک‌پذیر." },
    { id: 71, en_name: "Diphenoxylate", fa_name: "دیفنوکسیلات", fa_desc: "کنترل و توقف اسهال‌های حاد." },
    { id: 70, en_name: "Diphenhydramine", fa_name: "دیفن هیدرامین", fa_desc: "رفع علائم آلرژی، خارش شدید و کمک به خواب." },
    { id: 315, en_name: "Diphenhydramine Compound", fa_name: "دیفن هیدرامین کامپاند", fa_desc: "شربت ضد سرفه و خلط‌آور." },
    { id: 66, en_name: "Diclofenac", fa_name: "دیکلوفناک", fa_desc: "تسکین دردهای شدید مفصلی، التهاب و سنگ کلیه." },
    { id: 68, en_name: "Digoxin", fa_name: "دیگوکسین", fa_desc: "تقویت ضربان قلب در نارسایی‌های قلبی." },
    { id: 374, en_name: "Digoxin (Injection)", fa_name: "دیگوکسین (آمپول)", fa_desc: "داروی اورژانسی نارسایی قلبی و تنظیم ضربان." },
    { id: 69, en_name: "Diltiazem", fa_name: "دیلتیازم", fa_desc: "کنترل فشار خون و دردهای قلبی (آنژین)." },
    { id: 414, en_name: "Dimercaprol (BAL)", fa_name: "دیمرکاپرول", fa_desc: "پادزهر مسمومیت با فلزات سنگین (آرسنیک، جیوه، سرب) و گازهای شیمیایی تاول‌زا." },
    { id: 375, en_name: "Dimercaprol", fa_name: "دیمرکاپول", fa_desc: "پادزهر مسمومیت با فلزات سنگین (مثل آرسنیک و جیوه)." },
    { id: 314, en_name: "Dimenhydrinate", fa_name: "دیمن هیدرینات", fa_desc: "پیشگیری و درمان سرگیجه و حالت تهوع در سفر." },
    { id: 330, en_name: "Dimenhydrinate", fa_name: "دیمن هیدرینات", fa_desc: "پیشگیری و درمان حالت تهوع، استفراغ و سرگیجه ناشی از حرکت (ماشین‌گرفتگی)." },
    { id: 479, en_name: "Dinoprostone", fa_name: "دینوپروستون", fa_desc: "شیاف برای القای زایمان در شرایط اورژانسی و ختم بارداری." },
    { id: 328, en_name: "Dienogest", fa_name: "دینوژست", fa_desc: "داروی هورمونی برای درمان آندومتریوز و کاهش دردهای لگنی زنان." },
    { id: 72, en_name: "Divalproex", fa_name: "دیوالپروئکس", fa_desc: "کنترل تشنج، میگرن و اختلال دوقطبی." },
    { id: 221, en_name: "Rabeprazole", fa_name: "رابپرازول", fa_desc: "مهارکننده اسید معده برای درمان زخم‌های گوارشی." },
    { id: 435, en_name: "Racecadotril", fa_name: "راسکادوتریل", fa_desc: "درمان سریع اسهال حاد بدون ایجاد یبوست ثانویه." },
    { id: 222, en_name: "Raloxifene", fa_name: "رالوکسیفن", fa_desc: "پیشگیری و درمان پوکی استخوان در زنان یائسه." },
    { id: 223, en_name: "Ranitidine", fa_name: "رانیتیدین", fa_desc: "کاهش اسید معده و درمان سوزش سر دل." },
    { id: 225, en_name: "Repaglinide", fa_name: "رپاگلینید", fa_desc: "کاهش سریع قند خون بلافاصله بعد از غذا در دیابت." },
    { id: 224, en_name: "Remifentanil", fa_name: "رمی‌فنتانیل", fa_desc: "مسکن مخدر بسیار قوی و سریع برای عمل‌های جراحی." },
    { id: 233, en_name: "Ropinirole", fa_name: "روپینیرول", fa_desc: "درمان پارکینسون و سندرم پای بی‌قرار." },
    { id: 470, en_name: "Ropivacaine", fa_name: "روپیواکائین", fa_desc: "بی‌حسی موضعی و اپیدورال با کمترین عوارض قلبی." },
    { id: 234, en_name: "Rosuvastatin", fa_name: "روزوواستاتین", fa_desc: "داروی بسیار قوی برای کاهش شدید کلسترول خون." },
    { id: 383, en_name: "Rosiglitazone", fa_name: "روزیگلیتازون", fa_desc: "کاهنده قند خون در دیابت نوع ۲ (استفاده محدود به دلیل عوارض قلبی)." },
    { id: 432, en_name: "Rocuronium", fa_name: "روکورونیوم", fa_desc: "شل‌کننده عضلانی برای ثابت نگه‌داشتن بیمار حین جراحی اورژانسی." },
    { id: 226, en_name: "Ribavirin", fa_name: "ریباویرین", fa_desc: "داروی ضدویروس برای عفونت‌های شدید تنفسی و هپاتیت سی." },
    { id: 231, en_name: "Ritonavir", fa_name: "ریتوناویر", fa_desc: "داروی ضدویروس برای کنترل عفونت HIV." },
    { id: 230, en_name: "Risperidone", fa_name: "ریس‌پریدون", fa_desc: "داروی ضد جنون برای کنترل پرخاشگری و اسکیزوفرنی." },
    { id: 228, en_name: "Rifaximin", fa_name: "ریفاگزیمین", fa_desc: "آنتی‌بیوتیک گوارشی برای اسهال مسافرتی." },
    { id: 227, en_name: "Rifampin", fa_name: "ریفامپین", fa_desc: "آنتی‌بیوتیک اصلی در درمان سل و برخی عفونت‌های استخوانی." },
    { id: 232, en_name: "Rivaroxaban", fa_name: "ریواروکسابان", fa_desc: "رقیق‌کننده خون جدید برای جلوگیری از لخته در پا و ریه." },
    { id: 353, en_name: "Lidocaine/Prilocaine", fa_name: "کرم زایلاپی (EMLA)", fa_desc: "کرم بی‌حس‌کننده موضعی پوست قبل از تزریق، لیزر یا بخیه زدن." },
    { id: 401, en_name: "Activated Charcoal", fa_name: "زغال فعال (شارکول)", fa_desc: "پادزهر عمومی اورژانسی؛ برای جذب سموم خورده شده و جلوگیری از ورود سم به خون." },
    { id: 344, en_name: "Salicylic Acid/Lactic Acid", fa_name: "محلول زگیل", fa_desc: "سوزاندن و از بین بردن زگیل و میخچه." },
    { id: 399, en_name: "Zolpidem", fa_name: "زولپیدم", fa_desc: "داروی خواب‌آور سریع‌الاثر برای درمان کوتاه‌مدت بی‌خوابی." },
    { id: 299, en_name: "Zinc Oxide", fa_name: "زینک اکساید", fa_desc: "پماد محافظ پوست، تسکین سوختگی ادراری نوزادان و آفتاب‌سوختگی." },
    { id: 360, en_name: "Zinc Oxide (Ointment)", fa_name: "زینک اکساید", fa_desc: "محافظت پوست در برابر آفتاب، سوختگی پای نوزاد و التهاب." },
    { id: 400, en_name: "Zinc Oxide/Cod Liver Oil", fa_name: "پماد زینک و روغن ماهی", fa_desc: "پماد ترمیم‌کننده عالی برای سوختگی‌های سطحی و خراش‌ها." },
    { id: 319, en_name: "Gelofen", fa_name: "ژلوفن", fa_desc: "مسکن سریع و ضدالتهاب (کپسول ژلاتینی ایبوپروفن)." },
    { id: 443, en_name: "Piroxicam Gel", fa_name: "ژل پیروکسیکام", fa_desc: "مسکن موضعی برای رگ‌به‌رگ شدن و ضرب‌دیدگی‌ها در شرایط میدانی." },
    { id: 444, en_name: "Diclofenac Gel", fa_name: "ژل دیکلوفناک", fa_desc: "تسکین دردهای موضعی مفاصل و عضلات بدون عوارض گوارشی قرص." },
    { id: 7, en_name: "Albuterol (Salbutamol)", fa_name: "سالبوتامول", fa_desc: "گشادکننده راه‌های هوایی برای تسکین فوری حملات آسم." },
    { id: 236, en_name: "Salmeterol", fa_name: "سالمترول", fa_desc: "اسپری استنشاقی طولانی‌اثر برای پیشگیری از حملات آسم." },
    { id: 244, en_name: "Simethicone", fa_name: "سایمتیکون", fa_desc: "قطره/قرص ضد نفخ و از بین برنده گازهای مزاحم گوارشی." },
    { id: 246, en_name: "Sodium Bicarbonate", fa_name: "سدیم بی‌کربنات (جوش شیرین)", fa_desc: "تزریقی؛ برای احیای قلبی و اصلاح اسیدی شدن خون در اورژانس." },
    { id: 413, en_name: "Sodium Thiosulfate", fa_name: "سدیم تیوسولفات", fa_desc: "بخش سوم کیت پادزهر سیانور و خنثی‌کننده برخی سموم شیمیایی." },
    { id: 412, en_name: "Sodium Nitrite", fa_name: "سدیم نیتریت", fa_desc: "بخش دوم کیت پادزهر سیانور (تزریق وریدی)." },
    { id: 248, en_name: "Sodium Valproate", fa_name: "سدیم والپروات", fa_desc: "داروی کلیدی ضد تشنج، صرع و تثبیت خلق." },
    { id: 241, en_name: "Sertraline", fa_name: "سرترالین", fa_desc: "درمان افسردگی، وسواس و حملات پانیک." },
    { id: 482, en_name: "Dextran 40 / 70", fa_name: "سرم دکستران", fa_desc: "سرم حجم‌دهنده پلاسما؛ جایگزین موقت خون در خونریزی‌های وسیع میدانی." },
    { id: 229, en_name: "Ringer's Lactate", fa_name: "سرم رینگر لاکتات", fa_desc: "سرم حیاتی برای جبران حجم خون در شوک، خونریزی و سوختگی." },
    { id: 391, en_name: "Lactated Ringer's", fa_name: "سرم رینگر لاکتات", fa_desc: "سرم حیاتی برای جبران حجم خون در شوک و سوختگی." },
    { id: 408, en_name: "Tetanus Immune Globulin", fa_name: "سرم ضد کزاز (TIG)", fa_desc: "ایمنی فوری برای مجروحانی که زخم‌های عمیق، خاکی و ترکش‌خورده دارند." },
    { id: 247, en_name: "Sodium Chloride", fa_name: "سرم فیزیولوژی", fa_desc: "شستشوی زخم‌ها، چشم و جبران مایعات بدن." },
    { id: 327, en_name: "Dextrose 5% / 50%", fa_name: "سرم قندی (دکستروز)", fa_desc: "سرم حیاتی برای رفع سریع افت قند خون و تامین انرژی پایه." },
    { id: 407, en_name: "Rabies Immunoglobulin", fa_name: "سرم (ایمونوگلوبولین) هاری", fa_desc: "تزریق مستقیم در محل گازگرفتگی حیوانات برای خنثی‌سازی فوری ویروس." },
    { id: 485, en_name: "Hepatitis B Immune Globulin", fa_name: "سرم (ایمونوگلوبولین) هپاتیت بی", fa_desc: "تزریق فوری پس از فرو رفتن سوزن آلوده یا تماس با خون فرد مبتلا به هپاتیت." },
    { id: 37, en_name: "Cefazolin", fa_name: "سفازولین", fa_desc: "پیشگیری و درمان عفونت‌های شدید استخوانی و پوستی." },
    { id: 43, en_name: "Cephalexin", fa_name: "سفالکسین", fa_desc: "درمان عفونت‌های خفیف پوستی و ادراری." },
    { id: 39, en_name: "Cefepime", fa_name: "سفپیم", fa_desc: "درمان عفونت‌های مقاوم و شدید در بیمارستان." },
    { id: 369, en_name: "Cefepime", fa_name: "سفپیم", fa_desc: "آنتی‌بیوتیک بسیار قوی بیمارستانی برای عفونت‌های مرگبار." },
    { id: 316, en_name: "Ceftazidime", fa_name: "سفتازيديم", fa_desc: "آنتی‌بیوتیک تزریقی موثر بر باکتری‌های بسیار مقاوم (مثل سودومونا)." },
    { id: 308, en_name: "Ceftazidime", fa_name: "سفتازيديم", fa_desc: "درمان عفونت‌های مقاوم بیمارستانی و عفونت‌های خونی." },
    { id: 41, en_name: "Ceftriaxone", fa_name: "سفتریاکسون", fa_desc: "آنتی‌بیوتیک قوی تزریقی برای عفونت‌های شدید و مننژیت." },
    { id: 38, en_name: "Cefdinir", fa_name: "سفدینیر", fa_desc: "آنتی‌بیوتیک برای درمان عفونت‌های گوش، گلو و پوست." },
    { id: 307, en_name: "Cefotaxime", fa_name: "سفوتاکسیم", fa_desc: "آنتی‌بیوتیک تزریقی برای عفونت‌های شدید، ریوی و مننژیت." },
    { id: 315, en_name: "Cefotaxime", fa_name: "سفوتاکسیم", fa_desc: "آنتی‌بیوتیک تزریقی برای عفونت‌های شدید مثل مننژیت و ذات‌الریه." },
    { id: 40, en_name: "Cefixime", fa_name: "سفیکسیم", fa_desc: "درمان عفونت‌های مجاری ادراری، تنفسی و گوش میانی." },
    { id: 238, en_name: "Selegiline", fa_name: "سلژیلین", fa_desc: "درمان پارکینسون و در مواردی افسردگی." },
    { id: 42, en_name: "Celecoxib", fa_name: "سلکوکسیب", fa_desc: "تسکین دردهای مفصلی و روماتیسم با عوارض گوارشی کمتر." },
    { id: 239, en_name: "Selenium Sulfide", fa_name: "سلنیوم سولفاید", fa_desc: "شامپو برای درمان شوره شدید و عفونت‌های قارچی سر." },
    { id: 240, en_name: "Senna", fa_name: "سنا", fa_desc: "ملین گیاهی و قوی برای رفع یبوست." },
    { id: 386, en_name: "Sotalol", fa_name: "سوتالول", fa_desc: "داروی تنظیم‌کننده ریتم قلب برای آریتمی‌های خطرناک بطنی." },
    { id: 347, en_name: "Sotalol", fa_name: "سوتالول", fa_desc: "کنترل آریتمی‌های قلبی." },
    { id: 215, en_name: "Pseudoephedrine", fa_name: "سودوافدرین", fa_desc: "ضداحتقان و بازکننده سریع گرفتگی بینی در سرماخوردگی." },
    { id: 467, en_name: "Sevoflurane", fa_name: "سوفلوران", fa_desc: "گاز بیهوشی استنشاقی استاندارد برای حفظ بیهوشی در اتاق عمل." },
    { id: 252, en_name: "Sucralfate", fa_name: "سوکرالفیت", fa_desc: "پانسمان‌کننده دیواره معده برای درمان زخم معده." },
    { id: 388, en_name: "Sucralfate", fa_name: "سوکرالفیت", fa_desc: "ژل پوشش‌دهنده دیواره معده برای التیام سریع زخم معده." },
    { id: 390, en_name: "Suxamethonium", fa_name: "سوکینیل کولین", fa_desc: "شل‌کننده عضلانی فوق‌سریع برای لوله‌گذاری تنفسی در اورژانس." },
    { id: 471, en_name: "Sugammadex", fa_name: "سوگامادکس", fa_desc: "داروی نجات‌بخش برای خنثی کردن فوری فلج عضلانی حین بیهوشی." },
    { id: 93, en_name: "Ferrous Sulfate", fa_name: "سولفات آهن", fa_desc: "مکمل آهن برای پیشگیری و درمان کم‌خونی." },
    { id: 410, en_name: "Protamine Sulfate", fa_name: "سولفات پروتامین", fa_desc: "پادزهر برای توقف خونریزی ناشی از مصرف بیش از حد هپارین." },
    { id: 300, en_name: "Zinc Sulfate", fa_name: "سولفات روی (زینک)", fa_desc: "تقویت سیستم ایمنی، توقف ریزش مو و کمک به درمان اسهال." },
    { id: 149, en_name: "Magnesium Sulfate", fa_name: "سولفات منیزیم", fa_desc: "کنترل تشنج در زنان باردار (اکلامپسی) و رفع کمبود منیزیم." },
    { id: 393, en_name: "Magnesium Sulfate (Injection)", fa_name: "سولفات منیزیم (آمپول)", fa_desc: "کنترل تشنج در زنان باردار و رفع کمبود منیزیم." },
    { id: 389, en_name: "Sulfadiazine", fa_name: "سولفادیازین", fa_desc: "آنتی‌بیوتیک برای درمان توکسوپلاسموز و تب روماتیسمی." },
    { id: 254, en_name: "Sulfasalazine", fa_name: "سولفاسالازین", fa_desc: "درمان التهاب روده (کولیت) و روماتیسم مفصلی." },
    { id: 350, en_name: "Sulfasalazine", fa_name: "سولفاسالازین", fa_desc: "کاهش التهاب در روماتیسم و بیماری‌های التهابی روده." },
    { id: 253, en_name: "Sulfacetamide", fa_name: "سولفاستامید", fa_desc: "قطره چشمی برای درمان عفونت‌های باکتریایی چشم." },
    { id: 349, en_name: "Sulfamethoxazole", fa_name: "سولفامتوکسازول", fa_desc: "آنتی‌بیوتیک برای عفونت‌های ادراری و تنفسی." },
    { id: 255, en_name: "Sumatriptan", fa_name: "سوماترپتان", fa_desc: "داروی اختصاصی و سریع برای قطع حملات میگرن." },
    { id: 476, en_name: "Somatostatin", fa_name: "سوماتوستاتین", fa_desc: "کنترل اورژانسی خونریزی‌های گوارشی وسیع." },
    { id: 322, en_name: "Cyanocobalamin", fa_name: "سیانوکوبالامین (ویتامین B12)", fa_desc: "درمان کم‌خونی خطرناک (پرنیشیوز) و مشکلات عصبی ناشی از کمبود B12." },
    { id: 49, en_name: "Ciprofloxacin", fa_name: "سیپروفلوکساسین", fa_desc: "درمان عفونت‌های شدید گوارشی و مجاری ادراری." },
    { id: 451, en_name: "Ciprofloxacin Drops", fa_name: "قطره سیپروفلوکساسین (چشمی/گوشی)", fa_desc: "درمان عفونت‌های چرکی چشم و گوش خارجی." },
    { id: 324, en_name: "Cyproheptadine", fa_name: "سیپروهپتادین", fa_desc: "آنتی‌هیستامین، محرک اشتها و درمان آلرژی‌های خارش‌دار." },
    { id: 312, en_name: "Cyproheptadine", fa_name: "سیپروهپتادین", fa_desc: "ضدحساسیت قوی و محرک اشتها." },
    { id: 50, en_name: "Citalopram", fa_name: "سیتالوپرام", fa_desc: "درمان افسردگی و اختلالات اضطرابی." },
    { id: 44, en_name: "Cetirizine", fa_name: "سیتریزین", fa_desc: "کنترل علائم حساسیت فصلی، آبریزش بینی و خارش." },
    { id: 61, en_name: "Cyclobenzaprine", fa_name: "سیکلوبنزاپرین", fa_desc: "رفع اسپاسم و گرفتگی‌های عضلانی حاد." },
    { id: 323, en_name: "Cyclopentolate", fa_name: "سیکلوپنتولات", fa_desc: "قطره چشمی برای گشاد کردن مردمک پیش از معاینه و کاهش درد التهاب چشم." },
    { id: 62, en_name: "Cyclosporine", fa_name: "سیکلوسپورین", fa_desc: "جلوگیری از دفع پیوند اعضا و درمان خودایمنی‌های شدید." },
    { id: 242, en_name: "Sildenafil", fa_name: "سیلدنافیل (ویاگرا)", fa_desc: "درمان اختلال نعوظ و فشار خون شریانی ریوی." },
    { id: 243, en_name: "Silver Sulfadiazine", fa_name: "سیلور سولفادیازین", fa_desc: "پماد حیاتی برای پیشگیری و درمان عفونت در سوختگی‌ها." },
    { id: 245, en_name: "Simvastatin", fa_name: "سیمواستاتین", fa_desc: "کاهش کلسترول بد خون." },
    { id: 309, en_name: "Cinnarizine", fa_name: "سیناریزین", fa_desc: "کنترل سرگیجه، وزوز گوش و پیشگیری از ماشین‌گرفتگی." },
    { id: 318, en_name: "Cinnarizine", fa_name: "سیناریزین", fa_desc: "درمان سرگیجه، وزوز گوش و ماشین‌گرفتگی." },
    { id: 350, en_name: "Ketoconazole Shampoo", fa_name: "شامپو کتوکونازول", fa_desc: "درمان شوره شدید سر و قارچ‌های پوستی (تینئا ورسیکالر)." },
    { id: 335, en_name: "Famciclovir", fa_name: "فامسیکلوویر", fa_desc: "داروی ضد ویروس برای درمان زونا و تبخال تناسلی." },
    { id: 91, en_name: "Famotidine", fa_name: "فاموتیدین", fa_desc: "کاهش اسید معده و درمان سوزش سر دل." },
    { id: 465, en_name: "Formaldehyde", fa_name: "فرمالدهید", fa_desc: "استریل‌کننده محیطی برای پاکسازی اتاق عمل صحرایی." },
    { id: 94, en_name: "Fexofenadine", fa_name: "فکسوفنادین", fa_desc: "آنتی‌هیستامین فاقد خواب‌آلودگی برای درمان آلرژی." },
    { id: 98, en_name: "Fluticasone", fa_name: "فلوتیکازون", fa_desc: "اسپری کورتیکواستروئیدی برای کنترل آسم و آلرژی بینی." },
    { id: 339, en_name: "Flurbiprofen", fa_name: "فلوربی‌پروفن", fa_desc: "مسکن ضدالتهاب و قطره چشمی برای جلوگیری از تنگ شدن مردمک در جراحی." },
    { id: 381, en_name: "Fluorescein", fa_name: "فلورسین (قطره)", fa_desc: "قطره رنگی برای تشخیص خراشیدگی و آسیب قرنیه چشم." },
    { id: 448, en_name: "Fluorescein Drops", fa_name: "قطره فلورسئین", fa_desc: "قطره رنگی برای تشخیص پارگی قرنیه یا ورود ترکش و خاک به چشم." },
    { id: 337, en_name: "Fluocinolone", fa_name: "فلوسینولون", fa_desc: "پماد کورتیکواستروئیدی برای التهاب و خارش شدید پوستی." },
    { id: 338, en_name: "Fluphenazine", fa_name: "فلوفنازین", fa_desc: "داروی ضد جنون برای درمان اسکیزوفرنی و اختلالات روانی." },
    { id: 97, en_name: "Fluoxetine", fa_name: "فلوکستین", fa_desc: "درمان افسردگی، وسواس و پرخوری عصبی." },
    { id: 96, en_name: "Fluconazole", fa_name: "فلوکونازول", fa_desc: "درمان عفونت‌های قارچی سیستمیک و واژینال." },
    { id: 409, en_name: "Flumazenil", fa_name: "فلومازنیل", fa_desc: "پادزهر اوردوز و مسمومیت با داروهای خواب‌آور و آرام‌بخش (مثل دیازپام)." },
    { id: 382, en_name: "Flumazenil", fa_name: "فلومازنیل", fa_desc: "پادزهر اختصاصی برای اوردوز با داروهای خواب‌آور (بنزودیازپین‌ها)." },
    { id: 380, en_name: "Fentanyl", fa_name: "فنتانیل", fa_desc: "مسکن مخدر بسیار قوی برای دردهای جراحی و سرطان." },
    { id: 92, en_name: "Fentanyl", fa_name: "فنتانیل", fa_desc: "مسکن مخدر بسیار قوی برای دردهای شدید پس از عمل یا سرطان." },
    { id: 202, en_name: "Phenobarbital", fa_name: "فنوباربیتال", fa_desc: "داروی آرام‌بخش و کنترل‌کننده صرع و تشنج‌های مقاوم." },
    { id: 336, en_name: "Fenofibrate", fa_name: "فنوفیبرات", fa_desc: "کاهنده قوی تری‌گلیسیرید خون." },
    { id: 203, en_name: "Phenytoin", fa_name: "فنی‌توئین", fa_desc: "داروی کلیدی برای جلوگیری و کنترل تشنج و صرع." },
    { id: 338, en_name: "Phenylephrine", fa_name: "فنیل‌افرین", fa_desc: "ضد احتقان بینی و گشادکننده مردمک چشم." },
    { id: 375, en_name: "Phenylephrine", fa_name: "فنیل افرین", fa_desc: "ضداحتقان بینی و بالا برنده اورژانسی فشار خون در شوک." },
    { id: 438, en_name: "Formoterol", fa_name: "فورموترول", fa_desc: "اسپری گشادکننده طولانی‌اثر راه‌های هوایی برای بیماران آسمی." },
    { id: 100, en_name: "Furosemide", fa_name: "فوروزماید", fa_desc: "ادرارآور قوی برای کاهش ورم بدن و فشار خون." },
    { id: 416, en_name: "Fomepizole", fa_name: "فومپیزول", fa_desc: "پادزهر اورژانسی برای مسمومیت با الکل صنعتی (ميثانول) و ضدیخ." },
    { id: 473, en_name: "Physostigmine", fa_name: "فیزوستیگمین", fa_desc: "پادزهر مسمومیت با گیاهان سمی (مثل تاتوره) و برخی داروهای اعصاب." },
    { id: 95, en_name: "Finasteride", fa_name: "فیناستراید", fa_desc: "درمان ریزش موی مردانه و بزرگی پروستات." },
    { id: 335, en_name: "Pediatric Drops", fa_name: "قطره‌های اطفال", fa_desc: "مولتی‌ویتامین و آهن برای نوزادان و کودکان." },
    { id: 500, en_name: "Silver Nitrate Stick", fa_name: "قلم نیترات نقره", fa_desc: "قلم شیمیایی سوزاننده برای متوقف کردن سریع خون‌دماغ‌های شدید میدانی." },
    { id: 34, en_name: "Captopril", fa_name: "کاپتوپریل", fa_desc: "کاهش سریع فشار خون در اورژانس‌ها." },
    { id: 35, en_name: "Carbamazepine", fa_name: "کاربامازپین", fa_desc: "کنترل تشنج در صرع و درمان دردهای عصبی." },
    { id: 456, en_name: "Carbamide Peroxide", fa_name: "کاربامید پراکسید", fa_desc: "قطره برای نرم کردن و خروج جرم سفت شده گوش." },
    { id: 314, en_name: "Carbimazole", fa_name: "کاربی‌مازول", fa_desc: "داروی کاهنده هورمون تیروئید برای درمان پرکاری تیروئید." },
    { id: 36, en_name: "Carvedilol", fa_name: "کارودیلول", fa_desc: "درمان نارسایی قلبی و فشار خون بالا." },
    { id: 493, en_name: "Caspofungin", fa_name: "کاسپوفونژین", fa_desc: "ضدقارچ وریدی برای عفونت‌های قارچی کشنده در خون و اندام‌های داخلی." },
    { id: 367, en_name: "Caffeine", fa_name: "کافئین (تزریقی/خوراکی)", fa_desc: "محرک سیستم عصبی تنفسی نوزادان زودرس و مسکن همراه." },
    { id: 32, en_name: "Calamine", fa_name: "کالامین", fa_desc: "لوسیون موضعی برای تسکین خارش و التهاب خفیف پوست." },
    { id: 458, en_name: "Calamine/Pramoxine", fa_name: "کالامین پراموکسین", fa_desc: "لوسیون ترکیبی برای رفع خارش و بی‌حس کردن موضعی گزش حشرات." },
    { id: 445, en_name: "Capsaicin Cream", fa_name: "کرم کپسایسین", fa_desc: "کرم گرم‌کننده (عصاره فلفل) برای دردهای مزمن عصبی و عضلانی." },
    { id: 389, en_name: "Ketamine", fa_name: "کتامین", fa_desc: "داروی بیهوشی و تسکین درد در شرایط اورژانس و تروما." },
    { id: 125, en_name: "Ketamine", fa_name: "کتامین", fa_desc: "داروی بیهوشی و تسکین درد در شرایط اورژانس و تروما." },
    { id: 351, en_name: "Ketoprofen", fa_name: "کتوپروفن", fa_desc: "مسکن و ضدالتهاب برای دردهای عضلانی و اسکلتی." },
    { id: 128, en_name: "Ketotifen", fa_name: "کتوتیفن", fa_desc: "پیشگیری از حملات آسم و درمان آلرژی‌های مزمن." },
    { id: 127, en_name: "Ketorolac", fa_name: "کتورولاک", fa_desc: "مسکن بسیار قوی (مشابه مخدرها) برای دردهای حاد پس از جراحی." },
    { id: 322, en_name: "Ketorolac (Injection)", fa_name: "کتورولاک (آمپول)", fa_desc: "تسکین دردهای بسیار حاد مانند سنگ کلیه و پس از جراحی." },
    { id: 126, en_name: "Ketoconazole", fa_name: "کتوکونازول", fa_desc: "درمان عفونت‌های قارچی پوست، شوره شدید سر و قارچ ناخن." },
    { id: 59, en_name: "Codeine", fa_name: "کدئین", fa_desc: "تسکین دردهای متوسط و سرکوب سرفه‌های خشک." },
    { id: 354, en_name: "Vaginal Cream/Suppository", fa_name: "کرم/شیاف واژینال", fa_desc: "داروهای موضعی برای عفونت‌های اختصاصی زنان." },
    { id: 321, en_name: "Crotamiton", fa_name: "کروتامیتون", fa_desc: "لوسیون/کرم برای تسکین خارش‌های شدید پوستی و درمان گال." },
    { id: 311, en_name: "Cromolyn Sodium", fa_name: "کرومولین سدیم", fa_desc: "اسپری/قطره برای پیشگیری از آلرژی‌های شدید فصلی و تنفسی." },
    { id: 51, en_name: "Clarithromycin", fa_name: "کلاریترومایسین", fa_desc: "درمان عفونت‌های تنفسی و ریشه‌کن کردن میکروب معده." },
    { id: 323, en_name: "Loratadine/Pseudoephedrine", fa_name: "کلداکس / نوفلو", fa_desc: "تسکین علائم سرماخوردگی بدون ایجاد خواب‌آلودگی شدید." },
    { id: 45, en_name: "Chloramphenicol", fa_name: "کلرامفنیکل", fa_desc: "درمان عفونت‌های حاد باکتریایی چشم و گوش." },
    { id: 430, en_name: "Chloramine-T", fa_name: "کلرامین-تی", fa_desc: "پودر ضدعفونی‌کننده سطوح، تجهیزات پزشکی و زخم‌ها در شرایط صحرایی." },
    { id: 317, en_name: "Chlorpromazine", fa_name: "کلرپرومازین", fa_desc: "داروی ضدجنون قدیمی، آرام‌بخش و درمان سکسکه‌های بسیار مقاوم." },
    { id: 46, en_name: "Chlordiazepoxide", fa_name: "کلردیازپوکساید", fa_desc: "کاهش اضطراب و رفع تنش‌های عصبی." },
    { id: 48, en_name: "Chlorpheniramine", fa_name: "کلرفنیرامین", fa_desc: "درمان علائم سرماخوردگی و حساسیت." },
    { id: 370, en_name: "Chlorpheniramine (Injection)", fa_name: "کلرفنیرامین (آمپول)", fa_desc: "توقف سریع واکنش‌های حساسیتی و آلرژیک شدید." },
    { id: 47, en_name: "Chlorhexidine", fa_name: "کلرهگزیدین", fa_desc: "دهان‌شویه ضدعفونی‌کننده برای عفونت‌های لثه و دهان." },
    { id: 461, en_name: "Chlorhexidine Gluconate", fa_name: "کلرهگزیدین گلوکونات (محلول)", fa_desc: "محلول اسکراب جراحی برای ضدعفونی کردن دست جراح و پوست مجروح." },
    { id: 341, en_name: "Potassium Chloride", fa_name: "کلرید پتاسیم", fa_desc: "جبران اورژانسی افت پتاسیم خون." },
    { id: 417, en_name: "Calcium Chloride", fa_name: "کلرید کلسیم", fa_desc: "تزریق اورژانسی برای شوک‌های قلبی و مسمومیت با منیزیم." },
    { id: 312, en_name: "Calcitriol", fa_name: "کلسیتریول", fa_desc: "ویتامین D فعال برای تنظیم کلسیم در بیماران دیالیزی." },
    { id: 480, en_name: "Calcium Polystyrene Sulfonate", fa_name: "کلسیم پلی‌استایرن سولفونات", fa_desc: "کاهش سطح خطرناک پتاسیم خون (جلوگیری از ایست قلبی در آسیب‌های لهیدگی)." },
    { id: 306, en_name: "Calcium D", fa_name: "کلسیم دی", fa_desc: "مکمل ترکیبی برای تقویت استخوان‌ها و پیشگیری از پوکی استخوان." },
    { id: 33, en_name: "Calcium Carbonate", fa_name: "کلسیم کربنات", fa_desc: "مکمل کلسیم و خنثی‌کننده اسید معده." },
    { id: 313, en_name: "Calcium Gluconate", fa_name: "کلسیم گلوکونات", fa_desc: "تزریق اورژانسی برای افت شدید کلسیم خون و مسمومیت با منیزیم." },
    { id: 368, en_name: "Calcium Gluconate", fa_name: "کلسیم گلوکونات (سرم)", fa_desc: "پادزهر اورژانسی برای افزایش پتاسیم و افت کلسیم خون." },
    { id: 60, en_name: "Colchicine", fa_name: "کلشی‌سین", fa_desc: "درمان حملات حاد نقرس و کاهش التهاب مفاصل." },
    { id: 319, en_name: "Clemastine", fa_name: "کلماستین", fa_desc: "آنتی‌هیستامین و ضد حساسیت قوی با اثر خواب‌آوری." },
    { id: 53, en_name: "Clobetasol", fa_name: "کلوبتازول", fa_desc: "پماد بسیار قوی برای اگزماهای شدید و پسوریازیس." },
    { id: 56, en_name: "Clopidogrel", fa_name: "کلوپیدوگرل", fa_desc: "جلوگیری از تشکیل لخته خون و پیشگیری از سکته." },
    { id: 57, en_name: "Clotrimazole", fa_name: "کلوتریمازول", fa_desc: "درمان عفونت‌های قارچی پوست و واژن." },
    { id: 426, en_name: "Cloxacillin", fa_name: "کلوگزاسیلین", fa_desc: "آنتی‌بیوتیک اختصاصی برای عفونت‌های پوستی چرکی و کورک‌های شدید." },
    { id: 320, en_name: "Clomiphene", fa_name: "کلومیفن", fa_desc: "محرک تخمک‌گذاری برای درمان ناباروری در زنان." },
    { id: 54, en_name: "Clonazepam", fa_name: "کلونازپام", fa_desc: "کنترل تشنج و حملات پانیک." },
    { id: 55, en_name: "Clonidine", fa_name: "کلونیدین", fa_desc: "کاهش فشار خون اورژانسی و کنترل علائم ترک اعتیاد." },
    { id: 310, en_name: "Clidinium C", fa_name: "کلیدینیوم سی", fa_desc: "رفع اسپاسم و دردهای عصبی معده و روده." },
    { id: 52, en_name: "Clindamycin", fa_name: "کلیندامایسین", fa_desc: "درمان عفونت‌های دندانی، استخوانی و واژینال." },
    { id: 371, en_name: "Clindamycin (Topical)", fa_name: "کلیندامایسین (محلول)", fa_desc: "درمان موضعی جوش و آکنه عفونی." },
    { id: 58, en_name: "Co-amoxiclav", fa_name: "کوآموکسی کلاو", fa_desc: "درمان عفونت‌های مقاوم‌تر تنفسی و گوش." },
    { id: 285, en_name: "Trimethoprim/Sulfamethoxazole", fa_name: "کوتریموکسازول", fa_desc: "آنتی‌بیوتیک برای عفونت‌های ادراری، گوارشی و گوش." },
    { id: 423, en_name: "Colistin", fa_name: "کولیستین", fa_desc: "آنتی‌بیوتیک آخرین خط درمان برای باکتری‌های بیمارستانی مقاوم به همه داروها." },
    { id: 219, en_name: "Quetiapine", fa_name: "کوئتیآپین", fa_desc: "درمان اسکیزوفرنی و اختلال دوقطبی." },
    { id: 481, en_name: "Sodium Polystyrene Sulfonate", fa_name: "کی‌اکسالات", fa_desc: "پودر خوراکی/تنقیه برای دفع پتاسیم اضافی از بدن مجروحان زیر آوار مانده." },
    { id: 475, en_name: "Glucagon Emergency Kit", fa_name: "کیت اورژانس گلوکاگون", fa_desc: "تزریق عضلانی برای نجات بیمار دیابتی بی‌هوش شده بر اثر افت قند." },
    { id: 220, en_name: "Quinine", fa_name: "کینین", fa_desc: "درمان مالاریا و گرفتگی‌های شبانه عضلات پا." },
    { id: 101, en_name: "Gabapentin", fa_name: "گاباپنتین", fa_desc: "درمان دردهای عصبی (مثل گزگز دیابتی) و کمک به کنترل تشنج." },
    { id: 466, en_name: "Nitrous Oxide", fa_name: "گاز خنده‌آور (نیتروس اکساید)", fa_desc: "گاز تسکین‌دهنده درد و بی‌حسی در اورژانس و دندانپزشکی صحرایی." },
    { id: 341, en_name: "Ganciclovir", fa_name: "گانسیکلوویر", fa_desc: "ضدویروس قوی برای عفونت‌های چشمی ویروسی در افراد با نقص ایمنی." },
    { id: 108, en_name: "Guaifenesin", fa_name: "گایافنزین", fa_desc: "خلط‌آور، کمک به دفع ترشحات تنفسی در سرفه‌های خلط‌دار." },
    { id: 437, en_name: "Granisetron", fa_name: "گرانیسترون", fa_desc: "داروی ضد تهوع و استفراغ بسیار قوی." },
    { id: 343, en_name: "Griseofulvin", fa_name: "گریزئوفولوین", fa_desc: "داروی ضد قارچ خوراکی برای عفونت‌های مقاوم پوست، مو و ناخن." },
    { id: 298, en_name: "Xylometazoline", fa_name: "گزیلومتازولین", fa_desc: "قطره/اسپری ضداحتقان سریع برای گرفتگی شدید بینی." },
    { id: 462, en_name: "Glutaraldehyde", fa_name: "گلوتارالدهید", fa_desc: "مایع استریل‌کننده سرد برای ابزارهای جراحی در شرایط قطع برق." },
    { id: 107, en_name: "Glucagon", fa_name: "گلوکاگون", fa_desc: "داروی اورژانسی برای درمان افت بسیار شدید و خطرناک قند خون." },
    { id: 384, en_name: "Glucagon", fa_name: "گلوکاگون", fa_desc: "داروی اورژانسی برای درمان افت بسیار شدید و خطرناک قند خون." },
    { id: 342, en_name: "Glipizide", fa_name: "گلی‌پیزاید", fa_desc: "داروی خوراکی کاهنده قند خون در دیابت نوع ۲." },
    { id: 105, en_name: "Gliclazide", fa_name: "گلیکلازید", fa_desc: "کاهش قند خون در بیماران دیابتی." },
    { id: 106, en_name: "Glimepiride", fa_name: "گلی‌مپیراید", fa_desc: "کنترل دیابت نوع ۲." },
    { id: 104, en_name: "Glibenclamide", fa_name: "گلی بنکلامید", fa_desc: "کاهش و کنترل قند خون در دیابت نوع ۲." },
    { id: 129, en_name: "Labetalol", fa_name: "لابتالول", fa_desc: "کنترل فشار خون اورژانسی (مخصوصاً در مسمومیت حاملگی)." },
    { id: 390, en_name: "Labetalol", fa_name: "لابتالول", fa_desc: "کنترل فشار خون اورژانسی (مخصوصاً در زنان باردار)." },
    { id: 133, en_name: "Latanoprost", fa_name: "لاتانوپروست", fa_desc: "قطره چشمی برای کاهش فشار داخل چشم (آب‌سیاه)." },
    { id: 383, en_name: "Furosemide (Injection)", fa_name: "لازیکس (آمپول فوروزماید)", fa_desc: "تخلیه سریع آب تجمع‌یافته در ریه و بدن." },
    { id: 130, en_name: "Lactulose", fa_name: "لاکتولوز", fa_desc: "شربت ملین برای درمان یبوست مزمن و پاکسازی روده." },
    { id: 131, en_name: "Lamotrigine", fa_name: "لاموتریژین", fa_desc: "ضد تشنج و تثبیت‌کننده خلق در بیماران دوقطبی." },
    { id: 132, en_name: "Lansoprazole", fa_name: "لانسوپرازول", fa_desc: "کاهش اسید معده و درمان زخم‌های گوارشی." },
    { id: 143, en_name: "Loperamide", fa_name: "لوپرامید", fa_desc: "متوقف‌کننده سریع اسهال‌های حاد و غیرعفونی." },
    { id: 134, en_name: "Levetiracetam", fa_name: "لوتیراستام", fa_desc: "داروی خط اول برای کنترل تشنج و صرع." },
    { id: 144, en_name: "Loratadine", fa_name: "لوراتادین", fa_desc: "آنتی‌هیستامین فاقد خواب‌آلودگی برای درمان حساسیت فصلی." },
    { id: 355, en_name: "Loratadine/Pseudoephedrine", fa_name: "لوراتادین دی (کلاریناز)", fa_desc: "ترکیب ضدحساسیت و بازکننده بینی برای سرماخوردگی‌های شدید." },
    { id: 145, en_name: "Lorazepam", fa_name: "لورازپام", fa_desc: "آرام‌بخش سریع، رفع اضطراب حاد و متوقف‌کننده تشنج طولانی." },
    { id: 441, en_name: "Lornoxicam", fa_name: "لورنوکسیکام", fa_desc: "مسکن قوی برای دردهای حاد پس از جراحی یا تروما." },
    { id: 146, en_name: "Losartan", fa_name: "لوزارتان", fa_desc: "کنترل فشار خون بالا و محافظت از کلیه در بیماران دیابتی." },
    { id: 147, en_name: "Lovastatin", fa_name: "لوواستاتین", fa_desc: "کاهش کلسترول بد خون و پیشگیری از تصلب شرایین." },
    { id: 137, en_name: "Levothyroxine", fa_name: "لووتیروکسین", fa_desc: "هورمون جایگزین برای درمان کم‌کاری تیروئید." },
    { id: 352, en_name: "Levocetirizine", fa_name: "لووسیتریزین", fa_desc: "آنتی‌هیستامین نسل جدید برای حساسیت فصلی با کمترین میزان خواب‌آوری." },
    { id: 135, en_name: "Levofloxacin", fa_name: "لووفلوکساسین", fa_desc: "آنتی‌بیوتیک قوی برای عفونت‌های تنفسی، سینوزیت و مجاری ادراری." },
    { id: 136, en_name: "Levonorgestrel", fa_name: "لوونورژسترل", fa_desc: "قرص اورژانسی برای جلوگیری از بارداری ناخواسته." },
    { id: 142, en_name: "Lithium", fa_name: "لیتیوم", fa_desc: "تثبیت‌کننده اصلی خلق در اختلال دوقطبی و مانیا." },
    { id: 138, en_name: "Lidocaine", fa_name: "لیدوکائین", fa_desc: "بی‌حس‌کننده موضعی و داروی اورژانسی برای آریتمی قلبی." },
    { id: 392, en_name: "Lidocaine (Injection)", fa_name: "لیدوکائین (آمپول)", fa_desc: "بی‌حس‌کننده موضعی و داروی اورژانسی برای آریتمی قلبی." },
    { id: 141, en_name: "Lisinopril", fa_name: "لیزینوپریل", fa_desc: "کاهنده فشار خون و محافظت از قلب پس از سکته." },
    { id: 354, en_name: "Lindane", fa_name: "لیندان", fa_desc: "شامپو/لوسیون قوی برای درمان شپش و گال در خطوط آخر درمان." },
    { id: 139, en_name: "Linezolid", fa_name: "لینزولید", fa_desc: "آنتی‌بیوتیک بیمارستانی برای عفونت‌های باکتریایی بسیار مقاوم." },
    { id: 140, en_name: "Liothyronine", fa_name: "لیوتیرونین", fa_desc: "درمان کم‌کاری شدید و سریع تیروئید." },
    { id: 427, en_name: "Mafenide Acetate", fa_name: "مافنید استات", fa_desc: "پماد برای جلوگیری از عفونت در سوختگی‌های وسیع و عمیق (نفوذ بهتر از سیلور)." },
    { id: 452, en_name: "Dexamethasone/Neomycin", fa_name: "قطره ماکسیترول", fa_desc: "ترکیب کورتون و آنتی‌بیوتیک برای التهاب و عفونت شدید چشم." },
    { id: 150, en_name: "Mannitol", fa_name: "مانیتول", fa_desc: "داروی اورژانسی برای کاهش فشار داخل جمجمه پس از ضربه به سر." },
    { id: 394, en_name: "Mannitol", fa_name: "مانیتول", fa_desc: "سرم اورژانسی برای کاهش فشار داخل جمجمه پس از ضربه به سر." },
    { id: 169, en_name: "Minoxidil", fa_name: "ماینوکسیدیل", fa_desc: "محلول موضعی برای درمان ریزش مو / قرص برای فشار خون بسیار مقاوم." },
    { id: 151, en_name: "Mebendazole", fa_name: "مبندازول", fa_desc: "داروی ضد انگل برای درمان کرمک، آسکاریس و کرم شلاقی." },
    { id: 152, en_name: "Mebeverine", fa_name: "مبورین", fa_desc: "رفع اسپاسم و درد روده در سندرم روده تحریک‌پذیر (IBS)." },
    { id: 157, en_name: "Methadone", fa_name: "متادون", fa_desc: "مسکن مخدر قوی و داروی نگهدارنده در ترک اعتیاد." },
    { id: 166, en_name: "Metronidazole", fa_name: "مترونیدازول", fa_desc: "آنتی‌بیوتیک برای عفونت‌های دندانی، واژن و عفونت‌های گوارشی (آمیب)." },
    { id: 156, en_name: "Metformin", fa_name: "متفورمین", fa_desc: "داروی خط اول برای کنترل قند خون در دیابت نوع ۲ و تنبلی تخمدان." },
    { id: 165, en_name: "Metoprolol", fa_name: "متوپرولول", fa_desc: "کنترل فشار خون، تنظیم ضربان قلب و پیشگیری از آنژین." },
    { id: 160, en_name: "Methotrexate", fa_name: "متوترکسات", fa_desc: "داروی تضعیف‌کننده ایمنی برای روماتیسم شدید و برخی سرطان‌ها." },
    { id: 159, en_name: "Methocarbamol", fa_name: "متوکاربامول", fa_desc: "شل‌کننده عضلانی برای رفع گرفتگی‌های شدید اسکلتی." },
    { id: 164, en_name: "Metoclopramide", fa_name: "متوکلوپرامید", fa_desc: "ضد تهوع و استفراغ، تسریع حرکت و تخلیه معده." },
    { id: 478, en_name: "Methylergonovine", fa_name: "متیل‌ارگونووین", fa_desc: "تزریق برای متوقف کردن خونریزی‌های خطرناک رحمی پس از زایمان." },
    { id: 163, en_name: "Methylprednisolone", fa_name: "متیل‌پردنیزولون", fa_desc: "کورتون قوی برای التهابات شدید، آلرژی‌ها و حملات ام‌اس." },
    { id: 395, en_name: "Methylprednisolone (Injection)", fa_name: "متیل‌پردنیزولون (آمپول)", fa_desc: "کورتون قوی برای التهابات شدید، شوک و حملات ام‌اس." },
    { id: 161, en_name: "Methyldopa", fa_name: "متیل‌دوپا", fa_desc: "کنترل فشار خون بالا، به‌ویژه داروی ایمن در دوران بارداری." },
    { id: 162, en_name: "Methylphenidate", fa_name: "متیل‌فنیدات (ریتالین)", fa_desc: "درمان اختلال نقص توجه و بیش‌فعالی (ADHD) و حمله خواب." },
    { id: 474, en_name: "Methylene Blue", fa_name: "متیلن بلو", fa_desc: "پادزهر برای متهموگلوبینمی (کبودی شدید ناشی از مسمومیت شیمیایی/دارویی)." },
    { id: 158, en_name: "Methimazole", fa_name: "متی‌مازول", fa_desc: "درمان پرکاری تیروئید." },
    { id: 154, en_name: "Meropenem", fa_name: "مروپنم", fa_desc: "آنتی‌بیوتیک بسیار قوی بیمارستانی برای عفونت‌های مرگبار." },
    { id: 155, en_name: "Mesalamine", fa_name: "مسالامین", fa_desc: "کاهش التهاب در بیماری‌های روده (کولیت اولسراتیو و کرون)." },
    { id: 356, en_name: "Mefenamic Acid", fa_name: "مفنامیک اسید", fa_desc: "مسکن پرکاربرد برای دردهای دندان و دردهای دوران قاعدگی." },
    { id: 325, en_name: "Mefenamic Acid", fa_name: "مفنامیک اسید", fa_desc: "کاهش دردهای قاعدگی و دردهای خفیف دندانی." },
    { id: 357, en_name: "Melatonin", fa_name: "ملاتونین", fa_desc: "هورمون تنظیم خواب برای درمان بی‌خوابی و تنظیم ساعت بدن (جت‌لگ)." },
    { id: 153, en_name: "Meloxicam", fa_name: "ملوکسیکام", fa_desc: "ضددرد و التهاب مفاصل در روماتیسم و آرتروز." },
    { id: 326, en_name: "Menthol Salicylate", fa_name: "منتول سالیسیلات (پماد)", fa_desc: "تسکین دردهای عضلانی و مفصلی به صورت موضعی." },
    { id: 148, en_name: "Magnesium Hydroxide", fa_name: "منیزیم هیدروکساید", fa_desc: "شیر منیزیم؛ ملین و خنثی‌کننده اسید معده." },
    { id: 174, en_name: "Mupirocin", fa_name: "موپیروسین", fa_desc: "پماد آنتی‌بیوتیک برای زردزخم و عفونت‌های سطحی پوست." },
    { id: 173, en_name: "Morphine", fa_name: "مورفین", fa_desc: "قوی‌ترین مسکن مخدر اورژانسی برای دردهای شدید (مثل سکته قلبی یا تصادف)." },
    { id: 397, en_name: "Morphine Sulfate", fa_name: "مورفین", fa_desc: "قوی‌ترین مسکن مخدر اورژانسی برای دردهای حاد و تصادفات." },
    { id: 361, en_name: "Multivitamin", fa_name: "مولتی‌ویتامین", fa_desc: "تامین ویتامین‌های روزانه در شرایط سوءتغذیه یا کمبود دسترسی به غذای تازه." },
    { id: 328, en_name: "Multivitamin", fa_name: "مولتی ویتامین", fa_desc: "تامین نیازهای روزانه ویتامینی در شرایط سوءتغذیه." },
    { id: 360, en_name: "Mometasone", fa_name: "مومتازون", fa_desc: "اسپری بینی کورتون‌دار برای آلرژی‌های شدید و پولیپ بینی." },
    { id: 172, en_name: "Montelukast", fa_name: "مونتلوکاست", fa_desc: "قرص جویدنی برای پیشگیری از حملات آسم و آلرژی‌های مزمن فصلی." },
    { id: 168, en_name: "Midazolam", fa_name: "میدازولام", fa_desc: "آرام‌بخش و خواب‌آور اورژانسی قبل از جراحی یا برای توقف تشنج مقاوم." },
    { id: 396, en_name: "Midazolam", fa_name: "میدازولام", fa_desc: "آرام‌بخش اورژانسی قبل از جراحی یا توقف تشنج." },
    { id: 359, en_name: "Midodrine", fa_name: "میدودرین", fa_desc: "بالا بردن فشار خون در افرادی که دچار افت فشار خون وضعیتی می‌شوند." },
    { id: 170, en_name: "Mirtazapine", fa_name: "میرتازاپین", fa_desc: "درمان افسردگی شدید همراه با بی‌خوابی و بی‌اشتهایی." },
    { id: 171, en_name: "Misoprostol", fa_name: "میزوپروستول", fa_desc: "پیشگیری از زخم معده ناشی از مسکن‌ها و استفاده در زایمان/سقط." },
    { id: 358, en_name: "Miconazole/Hydrocortisone", fa_name: "پماد میکورت", fa_desc: "ترکیب ضدقارچ و کورتون برای درمان همزمان عفونت و خارش پوستی." },
    { id: 167, en_name: "Miconazole", fa_name: "میکونازول", fa_desc: "درمان عفونت‌های قارچی پوست، ناخن و واژن." },
    { id: 495, en_name: "Milrinone", fa_name: "میلرینون", fa_desc: "تزریق وریدی برای تقویت پمپاژ قلب در نارسایی‌های حاد و مقاوم قلبی." },
    { id: 177, en_name: "Naproxen", fa_name: "ناپروکسن", fa_desc: "مسکن و ضدالتهاب طولانی‌اثر برای دردهای مفصلی، دندانی و قاعدگی." },
    { id: 330, en_name: "Naphazoline/Antazoline", fa_name: "ناپریوین", fa_desc: "قطره چشمی برای رفع حساسیت و خارش شدید چشم." },
    { id: 329, en_name: "Naphazoline", fa_name: "نافازولین", fa_desc: "قطره چشمی/بینی برای رفع قرمزی و احتقان فوری." },
    { id: 362, en_name: "Nalbuphine", fa_name: "نالبوفین", fa_desc: "مسکن مخدر برای دردهای متوسط تا شدید در محیط‌های بیمارستانی." },
    { id: 176, en_name: "Naltrexone", fa_name: "نالتلروکسان", fa_desc: "کمک به ترک وابستگی و کاهش ولع مصرف در اعتیاد به الکل و مخدر." },
    { id: 175, en_name: "Naloxone", fa_name: "نالوکسان", fa_desc: "پادزهر اورژانسی و نجات‌بخش برای اوردوز با مواد مخدر." },
    { id: 398, en_name: "Naloxone", fa_name: "نالوکسان", fa_desc: "پادزهر اورژانسی و نجات‌بخش برای اوردوز با مواد مخدر." },
    { id: 363, en_name: "Naphazoline", fa_name: "نفازولین", fa_desc: "قطره چشمی/بینی برای رفع سریع قرمزی چشم و گرفتگی بینی." },
    { id: 364, en_name: "Naphazoline/Antazoline", fa_name: "نفازولین آنتازولین", fa_desc: "قطره چشمی برای رفع فوری قرمزی و خارش شدید چشم در آلرژی." },
    { id: 332, en_name: "Novafen", fa_name: "نوافن", fa_desc: "مسکن ترکیبی (استامینوفن، ایبوپروفن، کافئین) برای سردرد و دندان‌درد." },
    { id: 183, en_name: "Norepinephrine", fa_name: "نوراپی‌نفرین", fa_desc: "تزریق اورژانسی برای افزایش فشار خون در شوک‌های مرگبار." },
    { id: 184, en_name: "Nortriptyline", fa_name: "نورتریپتیلین", fa_desc: "درمان افسردگی، دردهای عصبی مزمن و شب‌ادراری." },
    { id: 367, en_name: "Norethisterone", fa_name: "نورتیسترون", fa_desc: "تنظیم چرخه قاعدگی و به تاخیر انداختن پریود در شرایط خاص." },
    { id: 385, en_name: "Silver Nitrate", fa_name: "نیترات نقره", fa_desc: "قلم سوزاننده برای متوقف کردن خونریزی‌های مویرگی (مثل خون‌دماغ) و زگیل." },
    { id: 345, en_name: "Silver Nitrate", fa_name: "نیترات نقره", fa_desc: "سوزاندن بافت‌های اضافی و بند آوردن خونریزی‌های سطحی." },
    { id: 418, en_name: "Nitroprusside", fa_name: "نیتروپروساید", fa_desc: "کاهش‌دهنده فوق‌سریع فشار خون در بحران‌های فشار خون (احتمال پارگی رگ)." },
    { id: 428, en_name: "Nitrofurazone", fa_name: "نیتروفورازون", fa_desc: "پماد موضعی برای پیشگیری از عفونت در پیوندهای پوستی و سوختگی‌ها." },
    { id: 331, en_name: "Nitrofurazone", fa_name: "نیتروفورازون (پماد)", fa_desc: "آنتی‌بیوتیک موضعی برای عفونت‌های سوختگی و زخم‌ها." },
    { id: 181, en_name: "Nitrofurantoin", fa_name: "نیتروفورانتوئین", fa_desc: "پیشگیری و درمان عفونت‌های دستگاه ادراری و مثانه." },
    { id: 400, en_name: "Nitroglycerin (IV)", fa_name: "نیتروگلیسیرین (تزریقی)", fa_desc: "گشادکننده عروق کرونر در زمان سکته قلبی." },
    { id: 182, en_name: "Nitroglycerin", fa_name: "نیتروگلیسیرین (TNG)", fa_desc: "قرص زیرزبانی/اسپری برای تسکین فوری درد قفسه سینه در بیماران قلبی." },
    { id: 185, en_name: "Nystatin", fa_name: "نیستاتین", fa_desc: "درمان قطعی عفونت‌های قارچی مثل برفک دهان و قارچ‌های روده‌ای." },
    { id: 180, en_name: "Nifedipine", fa_name: "نیفدیپین", fa_desc: "کاهنده فشار خون و کنترل دردهای قلبی؛ جلوگیری از زایمان زودرس." },
    { id: 366, en_name: "Nimodipine", fa_name: "نیمودیپین", fa_desc: "پیشگیری از اسپاسم عروق مغزی پس از خونریزی مغزی." },
    { id: 399, en_name: "Neostigmine", fa_name: "نئوستیگمین", fa_desc: "خنثی کردن شل‌کننده‌های اتاق عمل و درمان ضعف عضلانی." },
    { id: 179, en_name: "Neostigmine", fa_name: "نئوستیگمین", fa_desc: "درمان ضعف عضلانی (میاستنی گراویس) و خنثی کردن شل‌کننده‌های اتاق عمل." },
    { id: 178, en_name: "Neomycin", fa_name: "نئومایسین", fa_desc: "آنتی‌بیوتیک موضعی برای عفونت‌های پوستی یا قطره گوشی عفونت خارجی." },
    { id: 297, en_name: "Warfarin", fa_name: "وارفارین", fa_desc: "ضد انعقاد خون قوی برای پیشگیری از سکته و لخته." },
    { id: 419, en_name: "Vasopressin", fa_name: "وازوپرسین", fa_desc: "تزریق برای ایست قلبی و شوک‌های ناشی از خونریزی وسیع که به آدرنالین جواب نمی‌دهند." },
    { id: 327, en_name: "Metronidazole/Miconazole", fa_name: "پماد واژینال ترکیبی", fa_desc: "درمان عفونت‌های قارچی و باکتریایی زنانه." },
    { id: 406, en_name: "Rabies Vaccine", fa_name: "واکسن هاری", fa_desc: "پیشگیری از مرگ حتمی پس از گازگرفتگی توسط سگ، گرگ یا حیوانات وحشی." },
    { id: 288, en_name: "Valacyclovir", fa_name: "والاسیکلوویر", fa_desc: "ضدویروس قوی و طولانی‌اثر برای تبخال و زونا." },
    { id: 396, en_name: "Valproic Acid", fa_name: "والپروئیک اسید", fa_desc: "داروی ضدتشنج پرکاربرد، کنترل میگرن و تثبیت خلق." },
    { id: 289, en_name: "Valsartan", fa_name: "والسارتان", fa_desc: "کنترل فشار خون و درمان نارسایی قلبی." },
    { id: 290, en_name: "Vancomycin", fa_name: "وانکومایسین", fa_desc: "آنتی‌بیوتیک آخرین خط برای عفونت‌های بسیار مقاوم و مرگبار." },
    { id: 292, en_name: "Verapamil", fa_name: "وراپامیل", fa_desc: "کنترل فشار خون، پیشگیری از میگرن و آریتمی قلبی." },
    { id: 291, en_name: "Venlafaxine", fa_name: "ونلافاکسین", fa_desc: "ضد افسردگی و درمان اختلالات اضطرابی شدید." },
    { id: 293, en_name: "Vitamin A", fa_name: "ویتامین آ", fa_desc: "ضروری برای بینایی، پیشگیری از شب‌کوری و سلامت پوست." },
    { id: 358, en_name: "Vitamin E", fa_name: "ویتامین ای", fa_desc: "آنتی‌اکسیدان قوی برای سلامت پوست و قلب." },
    { id: 355, en_name: "Vitamin B1 (Thiamine)", fa_name: "ویتامین ب۱", fa_desc: "پیشگیری از آسیب‌های عصبی در شرایط استرس و سوءتغذیه." },
    { id: 356, en_name: "Vitamin B12", fa_name: "ویتامین ب۱۲ (آمپول)", fa_desc: "درمان کم‌خونی‌های شدید (پرنیشیوز) و ضعف اعصاب." },
    { id: 294, en_name: "Vitamin C", fa_name: "ویتامین ث (آسکوربیک اسید)", fa_desc: "تقویت ایمنی، کمک به ترمیم زخم و جذب بهتر آهن." },
    { id: 357, en_name: "Vitamin C (Injection)", fa_name: "ویتامین ث (آمپول)", fa_desc: "تقویت فوری سیستم ایمنی در اورژانس و تروما." },
    { id: 295, en_name: "Vitamin D3", fa_name: "ویتامین د۳", fa_desc: "درمان کمبود ویتامین د و پیشگیری از پوکی استخوان." },
    { id: 296, en_name: "Vitamin K1", fa_name: "ویتامین کا۱", fa_desc: "پادزهر اورژانسی برای توقف خونریزی و مسمومیت با وارفارین." },
    { id: 397, en_name: "Vitamin E", fa_name: "ویتامین E", fa_desc: "آنتی‌اکسیدان قوی برای محافظت از سلول‌ها." },
    { id: 376, en_name: "Phytomenadione (Vitamin K)", fa_name: "ویتامین K (تزریقی)", fa_desc: "پادزهر اورژانسی برای خونریزی‌های شدید ناشی از مصرف زیاد وارفارین." },
    { id: 109, en_name: "Haloperidol", fa_name: "هالوپریدول", fa_desc: "کنترل بی‌قراری شدید، اسکیزوفرنی و اختلالات حاد روانی." },
    { id: 385, en_name: "Haloperidol (Injection)", fa_name: "هالوپریدول (آمپول)", fa_desc: "کنترل سریع بی‌قراری شدید و حملات سایکوتیک." },
    { id: 499, en_name: "Haloperidol", fa_name: "هالوپریدول (آمپول)", fa_desc: "کنترل سریع بی‌قراری و هذیان شدید در مجروحان دچار موج‌گرفتگی یا تروما." },
    { id: 386, en_name: "Heparin", fa_name: "هپارین", fa_desc: "ضد انعقاد خون اورژانسی برای جلوگیری از لخته شدن." },
    { id: 110, en_name: "Heparin", fa_name: "هپارین", fa_desc: "ضد انعقاد خون اورژانسی برای جلوگیری از تشکیل یا رشد لخته." },
    { id: 111, en_name: "Hydralazine", fa_name: "هیدرالازین", fa_desc: "کاهش فشار خون بالا در شرایط اورژانسی و دوران بارداری." },
    { id: 387, en_name: "Hydralazine (Injection)", fa_name: "هیدرالازین (آمپول)", fa_desc: "کاهش فشار خون بالا در شرایط اورژانسی و مسمومیت حاملگی." },
    { id: 115, en_name: "Hydroxyzine", fa_name: "هیدروکسی‌زین", fa_desc: "ضدحساسیت، رفع خارش شدید و آرام‌بخش خفیف." },
    { id: 483, en_name: "Hydroxyethyl Starch", fa_name: "هیدروکسی اتیل استارچ (ولوون)", fa_desc: "سرم قدرتمند برای درمان شوک هموراژیک (کاهش حجم خون) در ترومای شدید." },
    { id: 344, en_name: "Hydroxychloroquine", fa_name: "هیدروکسی کلروکین", fa_desc: "درمان روماتیسم مفصلی، لوپوس و پیشگیری از مالاریا." },
    { id: 112, en_name: "Hydrochlorothiazide", fa_name: "هیدروکلروتیازید", fa_desc: "ادرارآور برای کاهش فشار خون و برطرف کردن ورم بدن." },
    { id: 113, en_name: "Hydrocortisone", fa_name: "هیدروکورتیزون", fa_desc: "کورتون (موضعی یا تزریقی) برای کاهش التهاب و حساسیت‌های شدید." },
    { id: 459, en_name: "Hydrocortisone Butyrate", fa_name: "هیدروکورتیزون بوتیرات", fa_desc: "پماد کورتونی متوسط برای اگزما و حساسیت‌های تماسی (مثل پیچک سمی)." },
    { id: 116, en_name: "Hyoscine (Scopolamine)", fa_name: "هیوسین", fa_desc: "رفع دل‌پیچه، اسپاسم‌های گوارشی و دردهای قاعدگی." },
    { id: 345, en_name: "Hyoscine Butylbromide", fa_name: "هیوسین بوتیل بروماید", fa_desc: "تسکین سریع دردهای اسپاسمی شکم، روده و سنگ کلیه." },
    { id: 402, en_name: "Potassium Iodide (KI)", fa_name: "یدید پتاسیم", fa_desc: "محافظت از غده تیروئید در برابر تشعشعات رادیواکتیو (حملات هسته‌ای)." },
    { id: 425, en_name: "Ampicillin/Sulbactam", fa_name: "یوناسین", fa_desc: "آنتی‌بیوتیک عالی برای عفونت‌های ناشی از گازگرفتگی حیوانات و انسان." }
];
window.medications = medications_sorted;
